docs/index.md

enhance by getting rid of duplicated words and providing a more precise description

docs: enhance intro page

---

docs/reference/command-lines.md
docs/reference/configuration.md

The reference of `greptime` command line.

docs: command line

---

docs/installation/kubernetes/gtctl.md
docs/installation/kubernetes/operator.md
docs/user-guide/reading-writing-data.md
docs/user-guide/supported-protocols/mysql.md

Main changes:
* Fixed MySQL ports in installation docs.
* Improve MySQL supporting doc.

docs: minor fixes for user guide and installation

---

docs/getting-started/distributed.md
docs/reference/configuration.md

fix: clode block and datanode mysql port

---

docs/developer-guide/get-started.md

Signed-off-by: Ruihang Xia <waynestxia@gmail.com>
Refer to https://github.com/GreptimeTeam/greptimedb/issues/563

docs: specify protoc version requirement

---

docs/user-guide/table-management.md

Main changes:
* Adds database management doc.
* Adds `desc table` to table management doc.

docs: database management and desc table

---

docs/getting-started/distributed.md

ready once https://github.com/GreptimeTeam/greptimedb/pull/576 merged

fix: add `--data-dir` and `--wal-dir`

---

docs/user-guide/table-management.md

Already supports dropping columns.

docs: describe dropping columns

---

docs/reference/configuration.md

Adds doc for s3  storage options.

docs: add s3 configuration

---

docs/.vitepress/config.ts

feat(config): add edit link

---

docs/getting-started/process-data-with-python.md

Insert python script should be with `schema` parameter

chore: fix getting started python script request error

---

docs/user-guide/java-sdk.md

Remove the gRPC-related parameters, as arrow-flight is now used instead of.

docs: java-sdk

---

docs/summary.yml
docs/user-guide/cli-repl.md

docs: add "Command Line Tool: REPL"

---

docs/reference/data-types.md

docs: data types

---

docs/.vitepress/theme/components/Layout.vue
docs/.vitepress/theme/utils.ts

Adding GA to give an insight into our website for documentation.

feat: added ga

---

docs/installation/download-pre-built.md

Format the `docs/installation/download-pre-built.md`.

chore: minor changes

---

docs/user-guide/supported-protocols/http-api.md

We now requires form data as post body

docs: update http-api.md for form post

---

docs/user-guide/authentication.md

This pr mainly adds explanation of how to setup authentication and how to connect with authentication information in GreptimeDB

chore: add authentication to user guide

---

docs/developer-guide/benchmarks/nyc-taxi.md
docs/summary.yml

Part of #267, document the usage of `nyc-taxi` bench tool

feat: document nyc-bench tool

---

docs/getting-started/create-a-time-series-table.md

add `IF NOT EXISTS` to create table clause.

feat: change quick start to create if not exist

---

docs/user-guide/reading-writing-data.md
docs/user-guide/supported-protocols/grpc.md

docs: update gRPC related docs

---

.gitignore
docs/.vitepress/config.ts
docs/developer-guide/how-to/how-to-write-sdk.md
docs/user-guide/java-sdk/quick-reference.md
docs/user-guide/promql/use-promql.md
docs/user-guide/reading-writing-data.md
docs/user-guide/supported-protocols/http-api.md
docs/user-guide/supported-protocols/prometheus.md

Turning on the check and resolve all existing dead links.

fix: dead links

---

docs/getting-started/visualize-data.md

docs: update Dashboard doc

---

docs/developer-guide/tests/unit-test.md

See also: https://nexte.st/book/installing-from-source.html

docs: update install cargo-nextest command

---

docs/reference/configuration.md

Storage compaction and manifest configuration.

docs: storage compaction and manifest options

---

docs/reference/sql/show.md

Adds `SHOW CREATE TABLE` statement
Close #324

docs: show create table

---

docs/reference/sdk/java.md

chore: Java link in reference

---

docs/developer-guide/how-to/how-to-write-sdk.md
docs/reference/sdk/go.md
docs/summary.yml
docs/user-guide/clients.md
docs/user-guide/query-data.md
docs/user-guide/write-data.md

docs: go sdk

---

docs/getting-started/overview.md
docs/index.md
docs/user-guide/query-data.md
docs/user-guide/scripts-&-functions/data-types.md
docs/user-guide/scripts-&-functions/getting-started.md
docs/user-guide/table-management.md
docs/user-guide/write-data.md

docs: emphasis schemaless writing

---

docs/user-guide/scripts-&-functions/data-types.md

Fix string typo in data-types.

docs: fix string typo in data types

---

docs/summary.yml
docs/user-guide/query-external-data.md

Add query external data docs.
- #338

feat: add query external data docs

---

docs/reference/sql/create.md

Add create external table reference.
close #338

feat: add create external table reference

---

docs/user-guide/operations/kubernetes.md

* update the link of the `kind` command
* replace `gtctl` with `./gtctl`
* split `helm` commands

chore: kubernetes operations

---

docs/developer-guide/how-to/how-to-use-tokio-console.md
docs/summary.yml

resolve comments from https://github.com/GreptimeTeam/greptimedb/pull/1512

docs: add "how to use tokio console"

---

docs/faq-and-others/faq.md

docs: update faq

---

docs/user-guide/operations/kubernetes.md

This PR adds the description of etcd cluster deployment. More operation content about kubernetes will be written in the future PRs.

docs: add etcd deployment

---

docs/developer-guide/overview.md
docs/reference/sql/alter.md
docs/user-guide/operations/configuration.md

Try to close #369, #386, #164 and #326

docs: tweak docs

---

docs/user-guide/clients.md

docs: add time zone for mysql protoocol

---

docs/zh/getting-started/overview.md
docs/zh/user-guide/scripts-&-functions/function.md
docs/zh/user-guide/write-data.md

docs: fix dead link

---

docs/changelog/biweekly-reports/latest-biweekly-report.md

docs: update biweekly report

---

docs/reference/sql/insert.md

Improve `insert` reference doc, demo:
* how to insert binary data
* how to insert special numeric values

docs: insert bianry data and special numeric values

---

docs/reference/sql/select.md

Demo how to query the lastest 5 minutes data.

docs: demo query latest data

---

docs/changelog/biweekly-reports/latest-biweekly-report.md

docs: update biweekly reports

---

docs/user-guide/concepts/storage-location.md
docs/user-guide/operations/configuration.md
docs/zh/user-guide/concepts/storage-location.md

Adds s3 compatible services list.

feat: adds s3 compatible services

---

docs/reference/telemetry.md

docs: how to disable telemetry

---

docs/greptimecloud/getting-started/quick-start/java.md
docs/zh/greptimecloud/getting-started/quick-start/java.md

Update jar version to export data every 5 seconds

docs: update download link of quick-start-java

---

docs/user-guide/query-data/promql.md

Fixes #537 
Add description Prometheus compatible API

docs: update prometheus api

---

docs/user-guide/write-data/influxdb-line.md
docs/zh/user-guide/write-data/influxdb-line.md

reference to https://github.com/GreptimeTeam/greptimedb/pull/2041 from @NiwakaDev

docs: omit influxdb timestamp

---

docs/greptimecloud/usage.md
docs/zh/greptimecloud/usage.md

This patch add description of our data retention policy for tech preview.

docs: data retention policy for greptimecloud

---

docs/getting-started/try-out-greptimedb.md
docs/getting-started/try-out-the-greptimedb-cluster.md
docs/index.md
docs/user-guide/scripts-&-functions/getting-started.md
docs/zh/user-guide/scripts-&-functions/getting-started.md

1. Seperate the original document to the two new docs: 'try-out-greptimedb.md' and 'try-out-the-greptimedb-cluster.md';
2. Refactor some formats;

docs: refactor getting started

---

docs/user-guide/cluster.md
docs/zh/user-guide/cluster.md

fix: create table bug for the latest version db

---

.github/pull_request_template.md
CONTRIBUTING.md
README.md

docs: update contributing.md

---

docs/summary.yml
docs/user-guide/clients/emqx.md
docs/zh/user-guide/clients/emqx.md

docs: add EMQX

---

docs/.vitepress/config/index.ts

refactor(config): change lang to en from zh

---

.markdownlint.yaml

style: temporarily close markdownlint

---

.github/pull_request_template.md
docs/en/v0.3/db-cloud-shared/clients/grafana-integration.md
docs/en/v0.3/db-cloud-shared/clients/otlp-integration.md
docs/en/v0.3/db-cloud-shared/clients/vector-integration.md
docs/en/v0.3/greptimecloud/integrations/influxdb.md
docs/en/v0.3/greptimecloud/integrations/mysql.md
docs/en/v0.3/greptimecloud/integrations/postgresql.md
docs/en/v0.3/greptimecloud/integrations/prometheus/quick-setup.md
docs/en/v0.3/greptimecloud/integrations/sdk-libraries/go.md
docs/en/v0.3/greptimecloud/integrations/sdk-libraries/java.md
docs/zh/v0.3/db-cloud-shared/clients/grafana-integration.md
docs/zh/v0.3/db-cloud-shared/clients/otlp-integration.md
docs/zh/v0.3/db-cloud-shared/clients/vector-integration.md
docs/zh/v0.3/greptimecloud/integrations/influxdb.md
docs/zh/v0.3/greptimecloud/integrations/mysql.md
docs/zh/v0.3/greptimecloud/integrations/postgresql.md
docs/zh/v0.3/greptimecloud/integrations/prometheus/quick-setup.md
docs/zh/v0.3/greptimecloud/integrations/sdk-libraries/go.md
docs/zh/v0.3/greptimecloud/integrations/sdk-libraries/java.md

This patch adds password placeholder in cloud integration docs, and to be render in our cloud console.

docs: update password placeholder in cloud integration docs

---

docs/.vitepress/config/common.ts
docs/.vitepress/theme/Layout.vue
docs/.vitepress/theme/index.ts
docs/.vitepress/theme/serverUtils.ts
docs/auto-imports.d.ts
docs/en/config/index.ts
docs/zh/config/index.ts

feat: add redirect for latest version

---

docs/.vitepress/config/common.ts
docs/.vitepress/theme/Layout.vue
docs/.vitepress/theme/style/custom.styl
docs/.vitepress/theme/style/sidebar.styl
docs/.vitepress/theme/utils.ts
docs/en/config/index.ts
docs/zh/config/index.ts

feat: add icon to sidebar

---

docs/en/v0.3/user-guide/query-data/sdk-libraries/java.md
docs/en/v0.4/user-guide/clients/sdk-libraries/java.md
docs/en/v0.4/user-guide/query-data/sdk-libraries/java.md
docs/en/v0.4/user-guide/write-data/sdk-libraries/java.md
docs/zh/v0.4/user-guide/clients/sdk-libraries/java.md
docs/zh/v0.4/user-guide/query-data/sdk-libraries/java.md
docs/zh/v0.4/user-guide/write-data/sdk-libraries/java.md

docs: v0.4 java sdk

---

docs/en/v0.4/user-guide/operations/configuration.md
docs/zh/v0.4/user-guide/operations/configuration.md

docs: update v0.4 configuration

---

docs/en/v0.4/developer-guide/how-to/how-to-use-tokio-console.md
docs/en/v0.4/developer-guide/how-to/how-to-write-sdk.md
docs/zh/v0.4/developer-guide/how-to/how-to-use-tokio-console.md
docs/zh/v0.4/developer-guide/how-to/how-to-write-sdk.md

docs: v0.4 howto

---

docs/en/v0.4/user-guide/table-management.md
docs/zh/v0.4/user-guide/table-management.md

docs: update table management for v0.4

---

docs/.vitepress/theme/style/custom.styl
docs/.vitepress/theme/style/sidebar.styl

fix: fix position of sidebar

---

README.md

fix(readme): fixed link problems in Readme

---

docs/en/v0.3/user-guide/clients/authentication.md
docs/en/v0.3/user-guide/clients/mysql.md
docs/en/v0.3/user-guide/clients/postgresql.md
docs/zh/v0.3/user-guide/clients/authentication.md
docs/zh/v0.3/user-guide/clients/mysql.md
docs/zh/v0.3/user-guide/clients/postgresql.md

chore: client/auth related update

---

docs/en/v0.4/reference/sdk/go.md
docs/en/v0.4/reference/sdk/java.md
docs/en/v0.4/user-guide/clients/sdk-libraries/go.md
docs/en/v0.4/user-guide/clients/sdk-libraries/java.md
docs/zh/v0.4/reference/sdk/go.md
docs/zh/v0.4/reference/sdk/java.md
docs/zh/v0.4/user-guide/clients/sdk-libraries/go.md
docs/zh/v0.4/user-guide/clients/sdk-libraries/java.md

docs: fix deadlink and some typos in sdk doc

---

docs/.vitepress/theme/Layout.vue
docs/.vitepress/theme/utils.ts
docs/en/config/index.ts

fix: change route path before page load

---

docs/en/v0.4/summary.yml
docs/en/v0.4/user-guide/operations/run-on-android.md
docs/zh/v0.4/user-guide/operations/run-on-android.md

docs(user-guide): add android running doc

---

docs/en/v0.4/user-guide/clients/vector.md
docs/zh/v0.4/user-guide/clients/vector.md

Accomplish the `client/vector` part in user guide. Both English and Chinese are updated.

docs(user-guide): accomplish client/vector document

---

docs/en/v0.4/user-guide/operations/configuration.md
docs/zh/v0.4/user-guide/operations/configuration.md

This PR updates the document about configuration

docs: update configuration docs for 0.4

---

docs/en/v0.4/developer-guide/datanode/data-persistence-indexing.md
docs/zh/v0.4/developer-guide/datanode/data-persistence-indexing.md

Fix doc for data persistence and indexing.

docs(develop-guide): doc for data format and peristence

---

docs/en/v0.3/faq-and-others/faq.md
docs/en/v0.4/db-cloud-shared/clients/grafana-integration.md
docs/zh/v0.4/db-cloud-shared/clients/grafana-integration.md

docs: update some docs about grafana

---

docs/en/v0.4/reference/data-types.md
docs/zh/v0.4/reference/data-types.md

update 0.4 reference data-types docs

docs(reference): update data-types

---

docs/en/v0.3/user-guide/query-data/sql.md
docs/en/v0.4/user-guide/query-data/sql.md
docs/en/v0.4/user-guide/write-data/sql.md
docs/zh/v0.3/user-guide/query-data/sql.md
docs/zh/v0.4/user-guide/query-data/sql.md
docs/zh/v0.4/user-guide/write-data/sql.md

use `monitor` table in user guide

docs: use `monitor` table in user guide

---

docs/en/config/index.ts
docs/zh/config/index.ts

fix: fixed a bug of article url while switch bewtten .com to .cn

---

docs/en/v0.3/user-guide/operations/gtctl.md
docs/en/v0.4/user-guide/operations/gtctl.md
docs/zh/v0.3/user-guide/operations/gtctl.md
docs/zh/v0.4/user-guide/operations/gtctl.md

fix: gtctl in navigation

---

docs/en/v0.4/user-guide/clients/influxdb-line.md
docs/zh/v0.4/user-guide/clients/influxdb-line.md

This pr mainly fix the url of influxdb v2.

docs: fix the url of influxdb v2

---

docs/en/v0.3/greptimecloud/integrations/sdk-libraries/go.md
docs/en/v0.3/user-guide/clients/sdk-libraries/go.md
docs/en/v0.3/user-guide/query-data/sdk-libraries/go.md
docs/en/v0.3/user-guide/write-data/sdk-libraries/go.md
docs/en/v0.4/greptimecloud/integrations/sdk-libraries/go.md
docs/en/v0.4/user-guide/clients/sdk-libraries/go.md
docs/en/v0.4/user-guide/query-data/sdk-libraries/go.md
docs/en/v0.4/user-guide/write-data/sdk-libraries/go.md
docs/zh/v0.3/greptimecloud/integrations/sdk-libraries/go.md
docs/zh/v0.3/user-guide/clients/sdk-libraries/go.md
docs/zh/v0.3/user-guide/query-data/sdk-libraries/go.md
docs/zh/v0.3/user-guide/write-data/sdk-libraries/go.md
docs/zh/v0.4/greptimecloud/integrations/sdk-libraries/go.md
docs/zh/v0.4/user-guide/clients/sdk-libraries/go.md
docs/zh/v0.4/user-guide/query-data/sdk-libraries/go.md
docs/zh/v0.4/user-guide/write-data/sdk-libraries/go.md

docs: update go sdk

---

docs/en/v0.4/reference/command-lines.md
docs/zh/v0.4/reference/command-lines.md

Update the `command-lines` v0.4 doc.

chore: update command line docs

---

docs/en/v0.4/developer-guide/datanode/storage-engine.md
docs/zh/v0.4/developer-guide/datanode/storage-engine.md

Translates the document to zh. Updates contents.

docs: update storage engine doc

---

docs/en/v0.4/user-guide/operations/configuration.md
docs/zh/v0.4/user-guide/operations/configuration.md

docs: update configuration docs

---

docs/en/v0.3/user-guide/operations/kubernetes.md
docs/en/v0.4/user-guide/operations/kubernetes.md
docs/zh/v0.3/user-guide/operations/kubernetes.md
docs/zh/v0.4/user-guide/operations/kubernetes.md

chore: update k8s helm operations

---

docs/en/v0.4/developer-guide/datanode/query-engine.md
docs/zh/v0.4/developer-guide/datanode/query-engine.md

Translate and update query engine part

docs(dev-guide): update query engine

---

docs/en/v0.4/user-guide/operations/configuration.md
docs/zh/v0.4/user-guide/operations/configuration.md

chore: meta client options

---

docs/.vitepress/config/common.ts

feat: just search latest version in local search

---

docs/en/v0.3/user-guide/operations/kubernetes.md
docs/en/v0.4/user-guide/operations/kubernetes.md
docs/zh/v0.3/user-guide/operations/kubernetes.md
docs/zh/v0.4/user-guide/operations/kubernetes.md

Use 'greptime/greptimedb-cluster' chart.

docs: use 'greptime/greptimedb-cluster' chart

---

docs/en/v0.4/user-guide/query-data/promql.md
docs/zh/v0.4/user-guide/query-data/promql.md

docs: update promql doc

---

.github/CODEOWNERS

Assign designTeam as the code owner of image files

chore: Assign @designTeam as the code owner of image files

---

docs/en/v0.4/user-guide/upgrade.md
docs/zh/v0.4/user-guide/upgrade.md

fix: correct default gRPC port in upgrade guide

---

.github/workflows/addDocsToS3BucketAWS.yml

chore: if source file not exist, delete s3 file resource

---

docs/en/v0.4/developer-guide/metasrv/selector.md
docs/zh/v0.4/developer-guide/metasrv/selector.md

This pr mainly update selector

docs: update selector

---

docs/en/v0.4/greptimecloud/greptimeai/langchain.md

langchain integration for greptimeai

feat: langchain integration for greptimeai

---

docs/en/v0.4/db-cloud-shared/tutorials/monitor-host-metrics/mysql-demo.md
docs/en/v0.4/getting-started/try-out-greptimedb.md
docs/en/v0.4/reference/data-types.md
docs/en/v0.4/reference/sql/create.md
docs/en/v0.4/user-guide/table-management.md
docs/zh/v0.4/db-cloud-shared/tutorials/monitor-host-metrics/mysql-demo.md
docs/zh/v0.4/getting-started/try-out-greptimedb.md
docs/zh/v0.4/reference/data-types.md
docs/zh/v0.4/reference/sql/create.md
docs/zh/v0.4/user-guide/table-management.md

docs: 'CURRENT_TIMESTAMP' -> 'CURRENT_TIMESTAMP()'

---

docs/en/v0.4/greptimecloud/greptimeai/langchain.md

Export OpenAI Key in LangChain Example

chore: export openai key in langchain example

---

docs/en/v0.4/faq-and-others/faq.md

chore: update faq.md

---

docs/.vitepress/theme/components/Footer.vue

refactor: adjust footer for mobile devices

---

.github/workflows/addDocsToS3BucketAWS.yml

Use "/*" path create cloudfront Invalidation.

chore: Update addDocsToS3BucketAWS.yml

---

docs/.vitepress/config/en.ts
docs/.vitepress/config/zh.ts

feat: update text of 404 page

---

docs/v0.4/en/reference/sql/copy.md

fix: fix typos

---

docs/v0.4/en/user-guide/scripts-&-functions/getting-started.md
docs/v0.4/zh/user-guide/scripts-&-functions/getting-started.md

fix: incorrect db name

---

docs/v0.4/en/developer-guide/tests/sqlness-test.md
docs/v0.4/zh/developer-guide/tests/sqlness-test.md

fix: correctly run specific sqlness test cases

---

docs/v0.4/en/reference/sql/alter.md
docs/v0.4/zh/reference/sql/alter.md

Adds doc about how to add a new column as a tag.

docs: adds new columns as tags

---

docs/v0.4/en/greptimecloud/greptimeai/langchain.md
docs/v0.4/en/greptimecloud/greptimeai/openai.md

docs: openai

---

docs/v0.4/en/changelog/biweekly-reports/latest-biweekly-report.md

update the latest biweekly report.

docs: update latest-biweekly-report.md

---

docs/v0.3/en/db-cloud-shared/clients/grafana-integration.md
docs/v0.3/zh/db-cloud-shared/clients/grafana-integration.md
docs/v0.4/en/db-cloud-shared/clients/grafana-integration.md
docs/v0.4/zh/db-cloud-shared/clients/grafana-integration.md

fix: grafana integration

---

docs/v0.4/en/reference/data-types.md
docs/v0.4/zh/reference/data-types.md

docs: decimal type

---

docs/v0.4/en/reference/sql/create.md
docs/v0.4/en/user-guide/concepts/storage-location.md
docs/v0.4/en/user-guide/operations/configuration.md
docs/v0.4/zh/reference/sql/create.md
docs/v0.4/zh/user-guide/concepts/storage-location.md
docs/v0.4/zh/user-guide/operations/configuration.md

* Improve configuration.
* Improve storage location.
* Improve create table reference.

feat: improve create reference, configuration and storage location docs

---

docs/v0.3/en/user-guide/scripts-&-functions/getting-started.md
docs/v0.4/en/user-guide/scripts-&-functions/getting-started.md
docs/v0.4/zh/user-guide/scripts-&-functions/getting-started.md

Add more explain in setting up Python for scripting

docs: script setup more details

---

docs/v0.4/en/developer-guide/metasrv/selector.md
docs/v0.4/en/user-guide/operations/configuration.md
docs/v0.4/zh/developer-guide/metasrv/selector.md
docs/v0.4/zh/user-guide/operations/configuration.md

As the title said
https://github.com/GreptimeTeam/greptimedb/pull/2962

chore: SelectType use snake case

---

docs/.vitepress/theme/style/docs.styl
docs/.vitepress/theme/style/vars.styl
docs/v0.4/en/index.md

refactor(style): adjust tag style of a contains code

---

docs/v0.5/en/getting-started/installation/greptimedb-cluster.md
docs/v0.5/en/getting-started/installation/greptimedb-standalone.md
docs/v0.5/zh/getting-started/installation/greptimedb-cluster.md
docs/v0.5/zh/getting-started/installation/greptimedb-standalone.md

docs: add Windows installation guides

---

docs/.vitepress/config/en.ts
docs/.vitepress/config/zh.ts

feat(config): update 2023 to 2024

---

docs/v0.5/en/user-guide/clients/prometheus.md

Small spelling change. Primiary => Primary

docs: spelling in prometheus.md

---

docs/v0.5/en/faq-and-others/faq.md

docs: update faq.md

---

docs/v0.5/en/user-guide/client-libraries/java.md

docs: ingester sdk java

---

docs/v0.6/en/greptimecloud/integrations/mysql.md
docs/v0.6/en/greptimecloud/integrations/postgresql.md
docs/v0.6/en/greptimecloud/integrations/streamlit.md
docs/v0.6/en/summary.yml
docs/v0.6/zh/greptimecloud/integrations/mysql.md
docs/v0.6/zh/greptimecloud/integrations/postgresql.md
docs/v0.6/zh/greptimecloud/integrations/streamlit.md

This patch adds:
- integration docs for streamlit
- url for mysql and postgres

docs: add streamlit integration docs

---

docs/v0.6/en/summary.yml
docs/v0.6/en/user-guide/operations/region-migration.md
docs/v0.6/zh/user-guide/operations/region-migration.md

feat: add region migration doc

---

docs/v0.5/en/summary.yml
docs/v0.5/en/user-guide/operations/kafka_remote_wal.md
docs/v0.5/zh/user-guide/operations/kafka_remote_wal.md

Add user guide for Kafka Remote WAL.
A subsequent PR will copy the content to v0.6 after this PR is merged.

docs: add user guide for kafka remote wal

---

docs/v0.6/en/reference/sql/copy.md
docs/v0.6/zh/reference/sql/copy.md

This PR addes the docs for `COPY DATABASE` statements.
fixes #427 #788 #793
fixes

docs:  copy database statements

---

docs/v0.6/en/summary.yml
docs/v0.6/en/user-guide/operations/kafka_remote_wal.md
docs/v0.6/zh/user-guide/operations/kafka_remote_wal.md

chore: copy kafka remote wal doc from 0.5 to 0.6

---

docs/v0.6/en/user-guide/client-libraries/java.md
docs/v0.6/zh/user-guide/client-libraries/java.md

feat: friendly api for table schema

---

docs/v0.6/en/greptimecloud/integrations/mysql.md
docs/v0.6/en/greptimecloud/integrations/postgresql.md

feat(cloud docs): update code block of cloud docs

---

docs/v0.6/en/greptimecloud/integrations/influxdb.md
docs/v0.6/en/greptimecloud/integrations/sdk-libraries/go.md
docs/v0.6/zh/greptimecloud/integrations/influxdb.md
docs/v0.6/zh/greptimecloud/integrations/sdk-libraries/go.md

* update SDK code
* add Java example code about Influxdb line protocol integration

docs: update SDK code for GreptimeCloud console

---

docs/v0.6/en/greptimecloud/integrations/sdk-libraries/go.md
docs/v0.6/en/user-guide/client-libraries/go.md
docs/v0.6/zh/greptimecloud/integrations/sdk-libraries/go.md
docs/v0.6/zh/user-guide/client-libraries/go.md

fix typo in ingester-go code samples

fix: ingester-go config

---

docs/.vitepress/theme/style/custom.styl

refactor(navbar): cancel capitalize of db version in navbar

---

docs/v0.7/en/greptimecloud/integrations/influxdb.md
docs/v0.7/zh/greptimecloud/integrations/influxdb.md

fix server url for influxdb v1 client

fix: server url for influxdb v1 client

---

docs/v0.7/en/user-guide/operations/configuration.md
docs/v0.7/en/user-guide/operations/tracing.md
docs/v0.7/zh/user-guide/operations/configuration.md
docs/v0.7/zh/user-guide/operations/tracing.md

docs about tracing sampler
Closes https://github.com/GreptimeTeam/docs/issues/816

docs: tracing sampler

---

docs/v0.7/en/user-guide/operations/region-migration.md
docs/v0.7/zh/user-guide/operations/region-migration.md

feat: update region migration docs

---

docs/v0.7/en/greptimecloud/integrations/sdk-libraries/java.md
docs/v0.7/en/user-guide/client-libraries/java.md
docs/v0.7/zh/greptimecloud/integrations/sdk-libraries/java.md
docs/v0.7/zh/user-guide/client-libraries/java.md

docs: add java tls docs

---

docs/v0.7/en/user-guide/operations/region-migration.md
docs/v0.7/zh/user-guide/operations/region-migration.md

fix: fix missing space

---

docs/v0.7/en/faq-and-others/faq.md

docs: update the latest faq.

---

docs/v0.7/zh/user-guide/operations/kafka-remote-wal.md

chore: typo

---

docs/v0.7/en/db-cloud-shared/clients/vector-integration.md
docs/v0.7/en/greptimecloud/integrations/vector.md
docs/v0.7/en/user-guide/clients/vector.md
docs/v0.7/zh/db-cloud-shared/clients/vector-integration.md
docs/v0.7/zh/greptimecloud/integrations/vector.md
docs/v0.7/zh/user-guide/clients/vector.md

docs: update vector for greptimecloud and tls

---

docs/v0.4/en/user-guide/operations/run-on-android.md
docs/v0.4/zh/user-guide/operations/run-on-android.md
docs/v0.5/en/user-guide/operations/run-on-android.md
docs/v0.5/zh/user-guide/operations/run-on-android.md
docs/v0.6/en/user-guide/operations/run-on-android.md
docs/v0.6/zh/user-guide/operations/run-on-android.md
docs/v0.7/en/user-guide/operations/run-on-android.md
docs/v0.7/zh/user-guide/operations/run-on-android.md

Fix the download link in "Run on Android pages"

docs: fix download link in android docs

---

docs/.vitepress/theme/Layout.vue
docs/tsconfig.json

chore: add @/* to tsconfig to improve devexp

---

docs/v0.7/en/contributor-guide/metasrv/overview.md
docs/v0.7/en/contributor-guide/metasrv/selector.md
docs/v0.7/zh/contributor-guide/metasrv/overview.md
docs/v0.7/zh/contributor-guide/metasrv/selector.md

As the title said. See https://github.com/GreptimeTeam/greptimedb/pull/3671

docs: rename MetaSrv to Metasrv

---

docs/release-notes/release-0-7-2.md
docs/v0.7/en/release-notes/all-releases.md
docs/v0.7/en/summary.yml

docs: update v0.7.2 release note

---

docs/v0.7/en/greptimecloud/usage-&-billing/request-capacity-unit.md
docs/v0.7/zh/greptimecloud/usage-&-billing/request-capacity-unit.md

This pr adds introduction of returned CU usage in HTTP response header from GreptimeCloud.
The content is processed with chatGPT, please check carefully.

chore: add doc for CU in HTTP response header

---

docs/v0.7/en/user-guide/write-data/prometheus.md
docs/v0.7/zh/user-guide/write-data/prometheus.md

This patch adds description for our newly added victoriametrics remote write support.

docs: add description for vm remote write

---

docs/release-notes/release-0-7-1.md
docs/release-notes/release-0-7-2.md

docs: highlight v0.7.2 critical bug fix

---

docs/v0.7/en/contributor-guide/how-to/how-to-write-sdk.md
docs/v0.7/zh/contributor-guide/how-to/how-to-write-sdk.md

docs: update "how to write a grpc sdk"

---

docs/v0.7/en/greptimecloud/integrations/emqx.md
docs/v0.7/en/greptimecloud/integrations/mindsdb.md
docs/v0.7/en/summary.yml

docs: add emqx and mindsdb integration for greptimecloud

---

README.md
docs/.vitepress/config/common.ts
docs/.vitepress/theme/style/custom.styl
docs/v0.3/en/index.md
docs/v0.3/zh/index.md
docs/v0.4/en/index.md
docs/v0.4/zh/index.md
docs/v0.5/en/index.md
docs/v0.5/zh/index.md
docs/v0.6/en/index.md
docs/v0.6/zh/index.md
docs/v0.7/en/index.md
docs/v0.7/zh/index.md

fix: fix width of image and update rewrites in global config

---

docs/v0.7/en/user-guide/query-data/sql.md
docs/v0.7/zh/user-guide/query-data/sql.md

docs: document distinct on

---

docs/v0.7/en/summary.yml
docs/v0.7/en/user-guide/operations/remote-wal/quick-start.md
docs/v0.7/zh/user-guide/operations/remote-wal/quick-start.md

Modify title of remote wal section.

refactor: modify title

---

docs/nightly/en/user-guide/query-data/promql.md
docs/nightly/zh/user-guide/query-data/promql.md
docs/v0.4/en/user-guide/query-data/promql.md
docs/v0.4/zh/user-guide/query-data/promql.md
docs/v0.5/en/user-guide/query-data/promql.md
docs/v0.5/zh/user-guide/query-data/promql.md
docs/v0.6/en/user-guide/query-data/promql.md
docs/v0.6/zh/user-guide/query-data/promql.md
docs/v0.7/en/user-guide/query-data/promql.md
docs/v0.7/zh/user-guide/query-data/promql.md

Remove the duplicate function `idelta`.

chore: remove the duplicate function

---

docs/nightly/en/user-guide/write-data/sql.md
docs/nightly/zh/user-guide/write-data/sql.md
docs/v0.7/en/user-guide/write-data/sql.md
docs/v0.7/zh/user-guide/write-data/sql.md

fix: title hierarchies

---

docs/v0.7/en/getting-started/installation/greptimedb-standalone.md
docs/v0.7/en/getting-started/quick-start/prerequisites.md
docs/v0.7/en/getting-started/quick-start/prometheus.md
docs/v0.7/en/getting-started/quick-start/vector.md
docs/v0.7/en/user-guide/client-libraries/go.md
docs/v0.7/en/user-guide/client-libraries/java.md
docs/v0.7/variates.yml
docs/v0.7/zh/getting-started/installation/greptimedb-standalone.md
docs/v0.7/zh/getting-started/quick-start/prerequisites.md
docs/v0.7/zh/getting-started/quick-start/prometheus.md
docs/v0.7/zh/getting-started/quick-start/vector.md
docs/v0.7/zh/user-guide/client-libraries/go.md
docs/v0.7/zh/user-guide/client-libraries/java.md

docs: use version variable in v0.7

---

docs/nightly/en/reference/sql/create.md
docs/nightly/en/reference/sql/functions.md
docs/nightly/en/summary.yml
docs/nightly/en/user-guide/concepts/features-that-you-concern.md
docs/nightly/en/user-guide/operations/admin.md
docs/nightly/en/user-guide/operations/back-up-&-restore-data.md
docs/nightly/en/user-guide/operations/region-migration.md
docs/nightly/en/user-guide/table-management.md
docs/nightly/zh/reference/sql/create.md
docs/nightly/zh/reference/sql/functions.md
docs/nightly/zh/summary-i18n.yml
docs/nightly/zh/user-guide/concepts/features-that-you-concern.md
docs/nightly/zh/user-guide/operations/admin.md
docs/nightly/zh/user-guide/operations/back-up-&-restore-data.md
docs/nightly/zh/user-guide/operations/region-migration.md
docs/nightly/zh/user-guide/table-management.md

* Add admin documents.
* Remove invalid `regions`.
* Add admin functions.

docs: admin documents

---

docs/nightly/en/reference/sql/compatibility.md
docs/nightly/en/reference/sql/create.md
docs/nightly/zh/reference/sql/compatibility.md
docs/nightly/zh/reference/sql/create.md
docs/v0.8/en/reference/sql/compatibility.md
docs/v0.8/en/reference/sql/create.md
docs/v0.8/zh/reference/sql/compatibility.md
docs/v0.8/zh/reference/sql/create.md

feat: improve sql compatibility documents

---

.github/workflows/addDocsToS3BucketAWS.yml

ci: automatically deploy zh documents

---

docs/.vitepress/config/common.ts

fix: do not search internal document dictionary

---

docs/.vitepress/config/en.ts
docs/.vitepress/config/zh.ts

fix: replace 404 twitter image with a new one

---

docs/.vitepress/config/common.ts
docs/.vitepress/config/en.ts
docs/.vitepress/config/zh.ts
docs/.vitepress/theme/style/search.styl

feat: use algolia search

---

docs/nightly/en/user-guide/query-data/overview.md
docs/nightly/zh/user-guide/query-data/overview.md

docs: refine the description of querying libs

---

docs/.vitepress/theme/style/sidebar.styl

style: sidebar

---

docs/nightly/variates.yml
docs/v0.8/en/getting-started/quick-start/prerequisites.md
docs/v0.8/en/getting-started/quick-start/prometheus.md
docs/v0.8/en/getting-started/quick-start/vector.md
docs/v0.8/en/user-guide/query-data/overview.md
docs/v0.8/variates.yml
docs/v0.8/zh/getting-started/quick-start/prerequisites.md
docs/v0.8/zh/getting-started/quick-start/prometheus.md
docs/v0.8/zh/getting-started/quick-start/vector.md
docs/v0.8/zh/user-guide/query-data/overview.md

docs: publish nightly and v0.8.2

---

docs/.vitepress/config/en.ts
docs/.vitepress/config/zh.ts
docs/public/robots.txt

feat: sitemap & robots.txt

---

docs/nightly/en/faq-and-others/faq.md
docs/nightly/en/user-guide/concepts/features-that-you-concern.md
docs/nightly/zh/summary-i18n.yml
docs/nightly/zh/user-guide/concepts/features-that-you-concern.md
docs/v0.8/en/faq-and-others/faq.md
docs/v0.8/en/user-guide/concepts/features-that-you-concern.md
docs/v0.8/zh/summary-i18n.yml
docs/v0.8/zh/user-guide/concepts/features-that-you-concern.md

docs: tweak faq

---

docs/nightly/en/reference/sql/create.md
docs/nightly/en/user-guide/table-management.md
docs/nightly/zh/reference/sql/create.md
docs/nightly/zh/user-guide/table-management.md
docs/v0.8/en/reference/sql/create.md
docs/v0.8/en/user-guide/table-management.md
docs/v0.8/zh/reference/sql/create.md
docs/v0.8/zh/user-guide/table-management.md

Adds documents for database options, close #904

docs: database options

---

docs/nightly/en/reference/sql/information-schema/schemata.md
docs/nightly/en/reference/sql/show.md
docs/nightly/zh/reference/sql/information-schema/schemata.md
docs/nightly/zh/reference/sql/show.md

Close #1013 for https://github.com/GreptimeTeam/greptimedb/pull/4174

docs: show database options and schemeta

---

docs/nightly/en/release-notes/all-releases.md
docs/nightly/en/summary.yml
docs/release-notes/release-0-8-2.md
docs/v0.8/en/release-notes/all-releases.md
docs/v0.8/en/summary.yml

docs: add v0.8.2 release note

---

docs/nightly/en/reference/sql/information-schema/partitions.md
docs/nightly/zh/reference/sql/information-schema/partitions.md
docs/v0.7/en/reference/sql/information-schema/partitions.md
docs/v0.7/zh/reference/sql/information-schema/partitions.md
docs/v0.8/en/reference/sql/information-schema/partitions.md
docs/v0.8/zh/reference/sql/information-schema/partitions.md

fix: partition rule

---

docs/nightly/zh/user-guide/logs/quick-start.md
docs/v0.9/zh/user-guide/logs/quick-start.md

fix: style

---

docs/nightly/en/reference/sql/copy.md
docs/nightly/zh/reference/sql/copy.md
docs/v0.6/en/reference/sql/copy.md
docs/v0.6/zh/reference/sql/copy.md
docs/v0.7/en/reference/sql/copy.md
docs/v0.7/zh/reference/sql/copy.md
docs/v0.8/en/reference/sql/copy.md
docs/v0.8/zh/reference/sql/copy.md
docs/v0.9/en/reference/sql/copy.md
docs/v0.9/zh/reference/sql/copy.md

fix: a place where copy database "to" should be "from"

---

docs/nightly/en/user-guide/overview.md
docs/nightly/zh/user-guide/overview.md
docs/v0.9/en/user-guide/overview.md
docs/v0.9/zh/user-guide/overview.md

fix: typo avatar

---

docs/nightly/en/getting-started/installation/greptimedb-cluster.md
docs/nightly/zh/getting-started/installation/greptimedb-cluster.md
docs/v0.8/en/getting-started/installation/greptimedb-cluster.md
docs/v0.8/zh/getting-started/installation/greptimedb-cluster.md
docs/v0.9/en/getting-started/installation/greptimedb-cluster.md
docs/v0.9/zh/getting-started/installation/greptimedb-cluster.md

Fix link to the helm charts document page.

docs: fix helm charts link

---

docs/nightly/en/summary.yml
docs/v0.6/en/summary.yml
docs/v0.7/en/summary.yml
docs/v0.8/en/summary.yml
docs/v0.9/en/summary.yml

chore: temporarily hide python scripts

---

docs/nightly/en/index.md
docs/nightly/en/user-guide/concepts/data-model.md
docs/nightly/en/user-guide/concepts/overview.md
docs/nightly/en/user-guide/concepts/why-greptimedb.md
docs/nightly/en/user-guide/overview.md
docs/nightly/zh/index.md
docs/release-notes/release-0-9-0.md
docs/v0.9/en/index.md
docs/v0.9/en/user-guide/concepts/data-model.md
docs/v0.9/en/user-guide/concepts/overview.md
docs/v0.9/en/user-guide/concepts/why-greptimedb.md
docs/v0.9/en/user-guide/overview.md
docs/v0.9/zh/index.md

Consistently use logs before events.

chore: logs before events

---

docs/nightly/en/user-guide/write-data/influxdb-line.md
docs/nightly/zh/user-guide/write-data/influxdb-line.md
docs/v0.9/en/user-guide/write-data/influxdb-line.md
docs/v0.9/zh/user-guide/write-data/influxdb-line.md

chore: refine the description for influxdb line protocol API

---

docs/nightly/en/user-guide/concepts/features-that-you-concern.md
docs/nightly/en/user-guide/concepts/storage-location.md
docs/nightly/zh/user-guide/concepts/features-that-you-concern.md
docs/nightly/zh/user-guide/concepts/storage-location.md
docs/v0.9/en/user-guide/concepts/features-that-you-concern.md
docs/v0.9/en/user-guide/concepts/storage-location.md
docs/v0.9/zh/user-guide/concepts/features-that-you-concern.md
docs/v0.9/zh/user-guide/concepts/storage-location.md

Fixed the storage location document.

fix: storage location

---

docs/v0.9/en/reference/sql/alter.md

Fix typo:  ALERT to ALTER
Fix typo:  ALERT to ALTER

docs: Update alter.md

---

docs/nightly/en/reference/sql/copy.md
docs/nightly/zh/reference/sql/copy.md
docs/v0.9/en/reference/sql/copy.md
docs/v0.9/zh/reference/sql/copy.md

close #431
Add target format orc for `Copy From`

feat: add target format orc

---

docs/nightly/en/user-guide/operations/configuration.md
docs/nightly/zh/user-guide/operations/configuration.md
docs/v0.9/en/user-guide/operations/configuration.md
docs/v0.9/zh/user-guide/operations/configuration.md

close #481 #488
add datanode client options & procedure options

docs: add datanode client options & procedure options

---

docs/nightly/en/user-guide/upgrade.md
docs/nightly/zh/user-guide/upgrade.md

As the title said.
Closes #1076

docs: new upgrade doc with copy database

---

.github/CODEOWNERS

- add fengjiachun to CODEOWNERS
- remove marketing from CODEOWNERS

chore: add fengjiachun to CODEOWNERS

---

docs/nightly/en/reference/sql/functions/overview.md
docs/nightly/en/user-guide/continuous-aggregation/expression.md
docs/nightly/en/user-guide/continuous-aggregation/overview.md
docs/nightly/en/user-guide/continuous-aggregation/query.md
docs/nightly/zh/reference/sql/functions/overview.md
docs/nightly/zh/user-guide/continuous-aggregation/expression.md
docs/nightly/zh/user-guide/continuous-aggregation/overview.md
docs/nightly/zh/user-guide/continuous-aggregation/query.md
docs/v0.9/en/reference/sql/functions/overview.md
docs/v0.9/en/user-guide/continuous-aggregation/expression.md
docs/v0.9/en/user-guide/continuous-aggregation/overview.md
docs/v0.9/en/user-guide/continuous-aggregation/query.md
docs/v0.9/zh/reference/sql/functions/overview.md
docs/v0.9/zh/user-guide/continuous-aggregation/expression.md
docs/v0.9/zh/user-guide/continuous-aggregation/overview.md
docs/v0.9/zh/user-guide/continuous-aggregation/query.md

- Change flow's use case to a better one which is more related
- add a simple rewrite guide for flow's query
- add reference to datafusion's scalar function and also added entry for some noteworth scalar function

docs: better flow usecase user guide

---

docs/nightly/en/user-guide/upgrade.md
docs/nightly/zh/user-guide/upgrade.md

As the title said
This PR closes #1112

docs: update export tool doc

---

docs/nightly/en/getting-started/installation/overview.md
docs/nightly/en/reference/sql/overview.md
docs/nightly/en/reference/sql/truncate.md
docs/nightly/en/summary.yml
docs/nightly/zh/reference/sql/overview.md
docs/nightly/zh/reference/sql/truncate.md
docs/v0.9/en/reference/sql/overview.md
docs/v0.9/en/reference/sql/truncate.md
docs/v0.9/en/summary.yml
docs/v0.9/zh/reference/sql/overview.md
docs/v0.9/zh/reference/sql/truncate.md

Adds `TRUNCATE TABLE table` reference.

docs: add truncate reference

---

docs/nightly/zh/user-guide/operations/disaster-recovery/dr-solution-based-on-cross-region-deployment-in-single-cluster.md
docs/v0.9/zh/user-guide/operations/disaster-recovery/dr-solution-based-on-cross-region-deployment-in-single-cluster.md

fix: image links

---

.github/workflows/addDocsToS3BucketAWS.yml

fix: zh deploy

---

.github/workflows/addDocsToS3BucketAWS.yml
docusaurus.config.ts
i18n/zh/docusaurus-plugin-content-docs/version-0.7.json
i18n/zh/docusaurus-plugin-content-docs/version-0.8.json

feat: docu algolia

---

README.md

fix: correct logo url in Readme

---

docs/user-guide/operations/configuration.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/operations/configuration.md

Add doc for remote wal authentication & TLS

feat: add doc for remote wal authentication & TLS

---

docs/user-guide/operations/configuration.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/operations/configuration.md

similar to https://github.com/GreptimeTeam/greptimedb/pull/4573 This pr adds examples to the backend field in metasrv config in the website 

docs: add backend configuration to metasrv doc

---

docusaurus.config.ts

fix: github edit link

---

docs/reference/sql/data-types.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/data-types.md
i18n/zh/docusaurus-plugin-content-docs/version-0.6/reference/sql/data-types.md
i18n/zh/docusaurus-plugin-content-docs/version-0.7/reference/sql/data-types.md
i18n/zh/docusaurus-plugin-content-docs/version-0.8/reference/sql/data-types.md
i18n/zh/docusaurus-plugin-content-docs/version-0.9/reference/sql/data-types.md
versioned_docs/version-0.6/reference/sql/data-types.md
versioned_docs/version-0.7/reference/sql/data-types.md
versioned_docs/version-0.8/reference/sql/data-types.md
versioned_docs/version-0.9/reference/sql/data-types.md

fix: change alias for timestamp(0) to TimestampSecond

---

docs/getting-started/installation/greptimedb-standalone.md
docs/user-guide/operations/deploy-on-kubernetes/deploy-greptimedb-cluster.md
docs/user-guide/operations/deploy-on-kubernetes/destroy-cluster.md
docs/user-guide/operations/deploy-on-kubernetes/greptimedb-operator.md
docs/user-guide/operations/deploy-on-kubernetes/overview.md
i18n/zh/docusaurus-plugin-content-docs/current/getting-started/installation/greptimedb-cluster.md
i18n/zh/docusaurus-plugin-content-docs/current/getting-started/installation/greptimedb-standalone.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/operations/deploy-on-kubernetes/deploy-greptimedb-cluster.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/operations/deploy-on-kubernetes/destroy-cluster.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/operations/deploy-on-kubernetes/greptimedb-operator.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/operations/deploy-on-kubernetes/overview.md

1. Update docs of K8s deployment;
2. Update some description of installation;

refactor: update docs of K8s deployment

---

CONTRIBUTING.md

docs: add variable placeholder to CONTRIBUTING.md

---

docs/user-guide/ingest-data/for-iot/grpc-sdks/go.md
docs/user-guide/ingest-data/for-iot/grpc-sdks/template.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/ingest-data/for-iot/grpc-sdks/go.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/ingest-data/for-iot/grpc-sdks/template.md

chore: refine the connection description for SDKs

---

CONTRIBUTING.md

docs: use the `.md` extension when contributing to this repo

---

docs/faq-and-others/faq.md
docs/reference/sql/admin.md
docs/reference/sql/functions/overview.md
docs/reference/sql/overview.md
docs/user-guide/concepts/features-that-you-concern.md
docs/user-guide/operations/admin.md
docs/user-guide/operations/compaction.md
docs/user-guide/operations/region-migration.md
i18n/zh/docusaurus-plugin-content-docs/current/faq-and-others/faq.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/admin.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/functions/overview.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/overview.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/concepts/features-that-you-concern.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/operations/admin.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/operations/compaction.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/operations/region-migration.md
sidebars.ts

* Fixed administration function statements, use `admin` instead of `select`.
* Adds `ADMIN` statement reference.
* Adds benchmark reports.
* Fixed some links.

feat: adds admin reference and updated some links

---

docs/greptimecloud/integrations/metabase.md
docs/greptimecloud/integrations/superset.md
docs/user-guide/integrations/metabase.md
docs/user-guide/integrations/overview.md
docs/user-guide/integrations/superset.md
i18n/zh/docusaurus-plugin-content-docs/current/greptimecloud/integrations/metabase.md
i18n/zh/docusaurus-plugin-content-docs/current/greptimecloud/integrations/superset.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/integrations/metabase.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/integrations/overview.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/integrations/superset.md
sidebars.ts

Add Apache Superset setup guide.

docs: superset and metabase integration

---

docs/greptimecloud/integrations/dbeaver.md
docs/reference/sql-tools.md
docs/user-guide/integrations/dbeaver.md
i18n/zh/docusaurus-plugin-content-docs/current/greptimecloud/integrations/dbeaver.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/sql-tools.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/integrations/dbeaver.md
sidebars.ts

docs: DBeaver integration

---

docs/user-guide/ingest-data/for-iot/grpc-sdks/overview.md
docs/user-guide/logs/quick-start.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/ingest-data/for-iot/grpc-sdks/overview.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/quick-start.md

* add doc for write log data using grpc protocol

docs: add doc for write log data using grpc protocol

---

docs/user-guide/administration/performance-tuning-tips.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/administration/performance-tuning-tips.md
i18n/zh/docusaurus-plugin-content-docs/version-0.9/user-guide/operations/performance-tuning-tips.md
versioned_docs/version-0.9/user-guide/operations/performance-tuning-tips.md

Update example to enable write cache

docs: update example

---

docs/enterprise/administration/disaster-recovery/dr-solution-based-on-active-active-failover.md
docs/enterprise/administration/disaster-recovery/overview.md
docs/enterprise/deployments/authentication.md
docs/enterprise/overview.md
docs/greptimecloud/usage-&-billing/byoc.md
docs/user-guide/administration/disaster-recovery/overview.md
docs/user-guide/deployments/authentication/overview.md
i18n/zh/docusaurus-plugin-content-docs/current.json
i18n/zh/docusaurus-plugin-content-docs/current/enterprise/administration/disaster-recovery/dr-solution-based-on-active-active-failover.md
i18n/zh/docusaurus-plugin-content-docs/current/enterprise/administration/disaster-recovery/overview.md
i18n/zh/docusaurus-plugin-content-docs/current/enterprise/deployments/authentication.md
i18n/zh/docusaurus-plugin-content-docs/current/enterprise/overview.md
i18n/zh/docusaurus-plugin-content-docs/current/greptimecloud/usage-&-billing/byoc.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/administration/disaster-recovery/overview.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/authentication/overview.md
sidebars.ts

docs: add GreptimeDB Enterprise

---

docs/getting-started/installation/overview.md
i18n/zh/docusaurus-plugin-content-docs/current/getting-started/installation/overview.md

docs: add status API

---

i18n/zh/docusaurus-plugin-content-docs/version-0.9.json

ref: https://github.com/GreptimeTeam/docs/pull/1220

fix: update the zh translation for the sidebar

---

blog/release-0-9-4.md

fix: add highlights

---

blog/release-0-9-4.md
blog/release-0-9-5.md
variables/variables-0.9.ts
variables/variables-nightly.ts

docs: publish v0.9.5

---

docs/user-guide/deployments/configuration.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/configuration.md
i18n/zh/docusaurus-plugin-content-docs/version-0.9/user-guide/deployments/configuration.md
versioned_docs/version-0.9/user-guide/deployments/configuration.md

Add the description of `overwrite_entry_start_id ` option

feat: add `overwrite_entry_start_id` option

---

docs/reference/sql/data-types.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/data-types.md
i18n/zh/docusaurus-plugin-content-docs/version-0.9/reference/sql/data-types.md
versioned_docs/version-0.9/reference/sql/data-types.md

fix #1230 #1212
add doc for json datatype

docs: add doc for json datatype

---

docs/user-guide/concepts/features-that-you-concern.md
docs/user-guide/query-data/sql.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/concepts/features-that-you-concern.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/query-data/sql.md

Add entrypoints for geo/json/functions.

docs: add functions and geo/json intro

---

i18n/zh/docusaurus-plugin-content-docs/version-0.6/db-cloud-shared/clients/otlp-integration.md
i18n/zh/docusaurus-plugin-content-docs/version-0.6/greptimecloud/integrations/influxdb.md
i18n/zh/docusaurus-plugin-content-docs/version-0.6/greptimecloud/integrations/mysql.md
i18n/zh/docusaurus-plugin-content-docs/version-0.6/greptimecloud/integrations/postgresql.md
i18n/zh/docusaurus-plugin-content-docs/version-0.6/greptimecloud/integrations/prometheus/quick-setup.md
i18n/zh/docusaurus-plugin-content-docs/version-0.6/greptimecloud/integrations/sdk-libraries/go.md
i18n/zh/docusaurus-plugin-content-docs/version-0.6/greptimecloud/integrations/sdk-libraries/java.md
i18n/zh/docusaurus-plugin-content-docs/version-0.7/db-cloud-shared/clients/otlp-integration.md
i18n/zh/docusaurus-plugin-content-docs/version-0.7/greptimecloud/integrations/influxdb.md
i18n/zh/docusaurus-plugin-content-docs/version-0.7/greptimecloud/integrations/mysql.md
i18n/zh/docusaurus-plugin-content-docs/version-0.7/greptimecloud/integrations/postgresql.md
i18n/zh/docusaurus-plugin-content-docs/version-0.7/greptimecloud/integrations/prometheus/quick-setup.md
i18n/zh/docusaurus-plugin-content-docs/version-0.7/greptimecloud/integrations/sdk-libraries/go.md
i18n/zh/docusaurus-plugin-content-docs/version-0.7/greptimecloud/integrations/sdk-libraries/java.md
versioned_docs/version-0.6/db-cloud-shared/clients/otlp-integration.md
versioned_docs/version-0.6/greptimecloud/integrations/influxdb.md
versioned_docs/version-0.6/greptimecloud/integrations/mysql.md
versioned_docs/version-0.6/greptimecloud/integrations/postgresql.md
versioned_docs/version-0.6/greptimecloud/integrations/prometheus/quick-setup.md
versioned_docs/version-0.6/greptimecloud/integrations/sdk-libraries/go.md
versioned_docs/version-0.6/greptimecloud/integrations/sdk-libraries/java.md
versioned_docs/version-0.7/db-cloud-shared/clients/otlp-integration.md
versioned_docs/version-0.7/greptimecloud/integrations/influxdb.md
versioned_docs/version-0.7/greptimecloud/integrations/mysql.md
versioned_docs/version-0.7/greptimecloud/integrations/postgresql.md
versioned_docs/version-0.7/greptimecloud/integrations/prometheus/quick-setup.md
versioned_docs/version-0.7/greptimecloud/integrations/sdk-libraries/go.md
versioned_docs/version-0.7/greptimecloud/integrations/sdk-libraries/java.md

fix: cloud urls

---

docs/user-guide/logs/manage-pipelines.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/manage-pipelines.md

Added a description of the relationship between the pipeline and the database.

chore: update manage pipeline doc

---

i18n/zh/docusaurus-plugin-content-docs/version-0.9/user-guide/migrate-to-greptimedb/migrate-from-mysql.md
versioned_docs/version-0.9/user-guide/migrate-to-greptimedb/migrate-from-mysql.md
versioned_sidebars/version-0.9-sidebars.json

docs: migrate from MySQL in v0.9

---

blog/release-0-9-3.md
docs/user-guide/deployments/configuration.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/configuration.md

docs: add datanode client config in frontend

---

docs/user-guide/deployments/deploy-on-kubernetes/getting-started.md
docs/user-guide/deployments/deploy-on-kubernetes/greptimedb-operator-management.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/deploy-on-kubernetes/getting-started.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/deploy-on-kubernetes/greptimedb-operator-management.md

1. Add the missing notes for the zh docs;
2. Add the description for how to modify the default cluster and namespace;
3. Modify some description of warning;
4. Add the note for how to deploy kind cluster in china mainland users;

refactor: add some notes and configurations

---

docs/reference/sql/information-schema/overview.md
docs/reference/sql/information-schema/region-statistics.md
docs/reference/sql/information-schema/tables.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/information-schema/overview.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/information-schema/region-statistics.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/information-schema/tables.md
sidebars.ts

docs: adds region_statistics refernece

---

docs/enterprise/deployments/audit-logging.md
docs/enterprise/overview.md
i18n/zh/docusaurus-plugin-content-docs/current/enterprise/deployments/audit-logging.md
i18n/zh/docusaurus-plugin-content-docs/current/enterprise/overview.md
sidebars.ts

docs: audit logging

---

variables/variables-nightly.ts

docs: update the nightly version

---

docs/greptimecloud/integrations/vector.md
i18n/zh/docusaurus-plugin-content-docs/current/greptimecloud/integrations/vector.md

Use default pipeline in demo configuration.

refactor: use default built-in pipeline

---

docs/db-cloud-shared/migrate/_migrate-from-prometheus.md
docs/greptimecloud/migrate-to-greptimecloud/migrate-from-prometheus.md
docs/user-guide/migrate-to-greptimedb/migrate-from-prometheus.md
i18n/zh/docusaurus-plugin-content-docs/current/db-cloud-shared/migrate/_migrate-from-prometheus.md
i18n/zh/docusaurus-plugin-content-docs/current/greptimecloud/integrations/prometheus.md
i18n/zh/docusaurus-plugin-content-docs/current/greptimecloud/migrate-to-greptimecloud/migrate-from-prometheus.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/migrate-to-greptimedb/migrate-from-prometheus.md
sidebars.ts

docs: migrate from Prometheus

---

docs/reference/sql/create.md
docs/user-guide/continuous-aggregation/manage-flow.md
docs/user-guide/continuous-aggregation/overview.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/create.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/continuous-aggregation/manage-flow.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/continuous-aggregation/overview.md
i18n/zh/docusaurus-plugin-content-docs/version-0.8/user-guide/continuous-aggregation/manage-flow.md
i18n/zh/docusaurus-plugin-content-docs/version-0.9/reference/sql/create.md
i18n/zh/docusaurus-plugin-content-docs/version-0.9/user-guide/continuous-aggregation/manage-flow.md
i18n/zh/docusaurus-plugin-content-docs/version-0.9/user-guide/continuous-aggregation/overview.md
versioned_docs/version-0.8/user-guide/continuous-aggregation/manage-flow.md
versioned_docs/version-0.9/reference/sql/create.md
versioned_docs/version-0.9/user-guide/continuous-aggregation/manage-flow.md
versioned_docs/version-0.9/user-guide/continuous-aggregation/overview.md

as title, fix type mismatch in create table in flow's user guide

fix: type in flow create table

---

docs/reference/sql/data-types.md
docs/user-guide/ingest-data/for-iot/grpc-sdks/go.md
docs/user-guide/ingest-data/for-iot/grpc-sdks/java.md
docs/user-guide/ingest-data/for-iot/grpc-sdks/template.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/data-types.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/ingest-data/for-iot/grpc-sdks/go.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/ingest-data/for-iot/grpc-sdks/java.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/ingest-data/for-iot/grpc-sdks/template.md

close #1276 
refer to: https://github.com/GreptimeTeam/greptimedb/issues/4872

docs: add JSON type for the gRPC SDKs

---

docs/reference/sql/show.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/show.md

docs: show create database

---

docs/user-guide/protocols/http.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/protocols/http.md

Add doc for setting http request timeout
close https://github.com/GreptimeTeam/docs/issues/1295

feat: add doc for setting http request timeout

---

docs/user-guide/deployments/configuration.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/configuration.md
i18n/zh/docusaurus-plugin-content-docs/version-0.9/user-guide/deployments/configuration.md
versioned_docs/version-0.9/user-guide/deployments/configuration.md

docs: add tls configurations

---

docs/reference/sql/case.md
docs/user-guide/query-data/sql.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/case.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/query-data/sql.md
sidebars.ts

docs: add `CASE` statement

---

docs/reference/sql/create.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/create.md

docs: add inverted index constraint

---

docs/user-guide/administration/disaster-recovery/back-up-&-restore-data.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/administration/disaster-recovery/back-up-&-restore-data.md

docs: timeout options

---

docs/user-guide/administration/disaster-recovery/back-up-&-restore-data.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/administration/disaster-recovery/back-up-&-restore-data.md

docs: timeout option example

---

blog/release-0-10-0.md

docs: v0.10.0 release node

---

.github/workflows/addDocsToS3BucketAWS.yml

chore: change docs bucket

---

blog/release-0-10-0.md

docs: add perf optimization to v0.10.0 highlights

---

blog/release-0-10-0.md
blog/release-0-10-1.md

docs: release note 0.10.1

---

variables/variables-0.10.ts
variables/variables-nightly.ts

fix: upgrade version to v0.10.1

---

docs/reference/sql/create.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/create.md
i18n/zh/docusaurus-plugin-content-docs/version-0.10/reference/sql/create.md
versioned_docs/version-0.10/reference/sql/create.md

fix: TTL option doc

---

variables/variables-0.10.ts
variables/variables-nightly.ts

chore: publish v0.10.2

---

docs/user-guide/administration/disaster-recovery/back-up-&-restore-data.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/administration/disaster-recovery/back-up-&-restore-data.md
i18n/zh/docusaurus-plugin-content-docs/version-0.10/user-guide/administration/disaster-recovery/back-up-&-restore-data.md
versioned_docs/version-0.10/user-guide/administration/disaster-recovery/back-up-&-restore-data.md

chore: fix the mistake args of cli cmd

---

.github/workflows/linter.yml
.typo.toml
.typos.toml

chore: merge typo configurations

---

batchreplace.txt
docs/faq-and-others/faq.md
docs/user-guide/logs/pipeline-config.md
i18n/zh/docusaurus-plugin-content-docs/current/faq-and-others/faq.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/pipeline-config.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/write-logs.md
i18n/zh/docusaurus-plugin-content-docs/version-0.10/faq-and-others/faq.md
i18n/zh/docusaurus-plugin-content-docs/version-0.10/user-guide/logs/pipeline-config.md
i18n/zh/docusaurus-plugin-content-docs/version-0.10/user-guide/logs/write-logs.md
i18n/zh/docusaurus-plugin-content-docs/version-0.8/faq-and-others/faq.md
i18n/zh/docusaurus-plugin-content-docs/version-0.9/faq-and-others/faq.md
i18n/zh/docusaurus-plugin-content-docs/version-0.9/user-guide/logs/pipeline-config.md
i18n/zh/docusaurus-plugin-content-docs/version-0.9/user-guide/logs/write-logs.md
versioned_docs/version-0.10/faq-and-others/faq.md
versioned_docs/version-0.10/user-guide/logs/pipeline-config.md
versioned_docs/version-0.7/faq-and-others/faq.md
versioned_docs/version-0.8/faq-and-others/faq.md
versioned_docs/version-0.9/faq-and-others/faq.md
versioned_docs/version-0.9/user-guide/logs/pipeline-config.md

chore: typos

---

.github/workflows/addDocsToS3BucketAWS.yml

Used to calculate file checksums and compare local files with files on S3 to determine whether they need to upload, download, or update.

ci: add checksum for upload to s3

---

docs/reference/http-endpoints.md
docs/user-guide/protocols/http.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/http-endpoints.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/protocols/http.md
sidebars.ts

List all available HTTP endpoints and their usages.

feat: add HTTP API list to reference

---

docs/greptimecloud/getting-started/vector.md
docs/greptimecloud/integrations/vector.md
docs/user-guide/ingest-data/for-observerbility/vector.md
i18n/zh/docusaurus-plugin-content-docs/current/greptimecloud/getting-started/vector.md
i18n/zh/docusaurus-plugin-content-docs/current/greptimecloud/integrations/vector.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/ingest-data/for-observerbility/vector.md

Recommend `new_naming` for vector config.

docs: recommend to turn on new_naming for vector

---

blog/release-0-11-0.md

docs: 0.11 release note

---

blog/release-0-11-0.md

Fixes typos in v0.11.0 release note

docs: fix typos in release note

---

docs/user-guide/administration/performance-tuning-tips.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/administration/performance-tuning-tips.md
i18n/zh/docusaurus-plugin-content-docs/version-0.11/user-guide/administration/performance-tuning-tips.md
versioned_docs/version-0.11/user-guide/administration/performance-tuning-tips.md

fixes https://github.com/GreptimeTeam/docs/issues/1360
It also adds a hint for primary keys.

docs: remove scan parallelism and add pk guide

---

docs/enterprise/autopilot/region-balancer.md
i18n/zh/docusaurus-plugin-content-docs/current/enterprise/autopilot/region-balancer.md
i18n/zh/docusaurus-plugin-content-docs/version-0.10/enterprise/autopilot/region-balancer.md
i18n/zh/docusaurus-plugin-content-docs/version-0.11/enterprise/autopilot/region-balancer.md
i18n/zh/docusaurus-plugin-content-docs/version-0.9/enterprise/autopilot/region-balancer.md
versioned_docs/version-0.10/enterprise/autopilot/region-balancer.md
versioned_docs/version-0.11/enterprise/autopilot/region-balancer.md
versioned_docs/version-0.9/enterprise/autopilot/region-balancer.md

fix: correct auto balancer options

---

docs/reference/sql/data-types.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/data-types.md
i18n/zh/docusaurus-plugin-content-docs/version-0.10/reference/sql/data-types.md
i18n/zh/docusaurus-plugin-content-docs/version-0.11/reference/sql/data-types.md
i18n/zh/docusaurus-plugin-content-docs/version-0.7/reference/sql/data-types.md
i18n/zh/docusaurus-plugin-content-docs/version-0.8/reference/sql/data-types.md
i18n/zh/docusaurus-plugin-content-docs/version-0.9/reference/sql/data-types.md
versioned_docs/version-0.10/reference/sql/data-types.md
versioned_docs/version-0.11/reference/sql/data-types.md
versioned_docs/version-0.7/reference/sql/data-types.md
versioned_docs/version-0.8/reference/sql/data-types.md
versioned_docs/version-0.9/reference/sql/data-types.md

fix: datatypes typos

---

blog/release-0-11-1.md

docs: 0.11.1 changelog

---

docs/contributor-guide/flownode/overview.md

update flow's contributor guide

docs: update flow's contributor guide

---

docs/user-guide/ingest-data/for-iot/grpc-sdks/go.md
docs/user-guide/ingest-data/for-iot/grpc-sdks/java.md
docs/user-guide/ingest-data/for-iot/grpc-sdks/template.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/ingest-data/for-iot/grpc-sdks/go.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/ingest-data/for-iot/grpc-sdks/java.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/ingest-data/for-iot/grpc-sdks/template.md
variables/variables-0.11.ts
variables/variables-nightly.ts

docs: set table options via gRPC SDK

---

docs/user-guide/deployments/deploy-on-kubernetes/common-helm-chart-configurations.md
docs/user-guide/deployments/deploy-on-kubernetes/monitoring/cluster-monitoring-deployment.md
docs/user-guide/deployments/deploy-on-kubernetes/overview.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/deploy-on-kubernetes/common-helm-chart-configurations.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/deploy-on-kubernetes/monitoring/cluster-monitoring-deployment.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/deploy-on-kubernetes/overview.md
sidebars.ts

Add common helm chart configurations

docs: add common helm chart configurations

---

docs/user-guide/deployments/configuration.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/configuration.md

add postgres kvbackend config docs

feat: add postgres kvbackend config docs

---

.github/workflows/addDocsToS3BucketAWS.yml

chore: deploy ZH doc when PR merged

---

docs/user-guide/administration/manage-etcd.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/administration/manage-etcd.md
i18n/zh/docusaurus-plugin-content-docs/version-0.11/user-guide/administration/manage-etcd.md
versioned_docs/version-0.11/user-guide/administration/manage-etcd.md

chore: modify manage-etcd docs symbol style

---

i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/functions/geo.md
i18n/zh/docusaurus-plugin-content-docs/version-0.11/reference/sql/functions/geo.md

fix: untranslated content

---

docs/user-guide/concepts/storage-location.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/concepts/storage-location.md
i18n/zh/docusaurus-plugin-content-docs/version-0.11/user-guide/concepts/storage-location.md
versioned_docs/version-0.11/user-guide/concepts/storage-location.md

* Fixed the storage location documents.

fix: storage location doc

---

.github/workflows/bump-nightly-version.yml
.github/workflows/bump-patch-version.yml
.github/workflows/bump-version.yml

chore: bump version title

---

.github/workflows/addDocsToS3BucketAWS.yml

chore: deploy AWS on push

---

docs/user-guide/protocols/loki.md
docs/user-guide/protocols/overview.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/protocols/loki.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/protocols/overview.md
i18n/zh/docusaurus-plugin-content-docs/version-0.11/user-guide/protocols/loki.md
i18n/zh/docusaurus-plugin-content-docs/version-0.11/user-guide/protocols/overview.md
sidebars.ts
versioned_docs/version-0.11/user-guide/protocols/loki.md
versioned_docs/version-0.11/user-guide/protocols/overview.md
versioned_sidebars/version-0.11-sidebars.json

chore: add doc for loki protocol

---

docs/user-guide/ingest-data/for-observerbility/elasticsearch.md
docs/user-guide/protocols/elasticsearch.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/ingest-data/for-observerbility/elasticsearch.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/protocols/elasticsearch.md
sidebars.ts

Add the docs of ingesting log data by elasticsearch protocol.

docs: add elasticsearch ingestion

---

.github/workflows/addDocsToS3BucketAWS.yml

https://github.com/peak/s5cmd
This tool make uploading files faster.

ci: upload files to s3 using s5cmd

---

docs/user-guide/deployments/deploy-on-kubernetes/common-helm-chart-configurations.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/deploy-on-kubernetes/common-helm-chart-configurations.md
i18n/zh/docusaurus-plugin-content-docs/version-0.11/user-guide/deployments/deploy-on-kubernetes/common-helm-chart-configurations.md
versioned_docs/version-0.11/user-guide/deployments/deploy-on-kubernetes/common-helm-chart-configurations.md

Add the following configuration:
- Object Storage Configuration
- Prometheus Monitor Configuration
- Debug pod Configuration

feat: Add more greptimedb-cluster helm chart values configuration

---

docs/faq-and-others/faq.md
i18n/zh/docusaurus-plugin-content-docs/current/faq-and-others/faq.md

docs: update the faq

---

docs/getting-started/installation/greptimedb-standalone.md
docs/reference/command-lines.md
docs/user-guide/administration/remote-wal/quick-start.md
docs/user-guide/deployments/configuration.md
i18n/zh/docusaurus-plugin-content-docs/current/getting-started/installation/greptimedb-standalone.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/command-lines.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/administration/remote-wal/quick-start.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/configuration.md

docs: rename rpc option names

---

.github/workflows/addDocsToS3BucketAWS.yml

fix: deploy zh doc

---

docs/user-guide/query-data/promql.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/query-data/promql.md

Add description for database matcher. Also update wording of PromQL compatibility.

docs: add database matcher

---

docs/user-guide/administration/manage-data/region-migration.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/administration/manage-data/region-migration.md
i18n/zh/docusaurus-plugin-content-docs/version-0.10/user-guide/administration/manage-data/region-migration.md
i18n/zh/docusaurus-plugin-content-docs/version-0.11/user-guide/administration/manage-data/region-migration.md
versioned_docs/version-0.10/user-guide/administration/manage-data/region-migration.md
versioned_docs/version-0.11/user-guide/administration/manage-data/region-migration.md

Correct region migration note
close #1180

chore: correct region migration note

---

docs/user-guide/deployments/deploy-on-kubernetes/configure-frontend-groups.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/deploy-on-kubernetes/configure-frontend-groups.md
i18n/zh/docusaurus-plugin-content-docs/version-0.12/user-guide/deployments/deploy-on-kubernetes/configure-frontend-groups.md

chore: modify frontend group description

---

docs/user-guide/logs/quick-start.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/quick-start.md
i18n/zh/docusaurus-plugin-content-docs/version-0.12/user-guide/logs/quick-start.md
versioned_docs/version-0.12/user-guide/logs/quick-start.md

chore: remove matches

---

docs/user-guide/ingest-data/for-iot/grpc-sdks/java.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/ingest-data/for-iot/grpc-sdks/java.md

docs: java ingester sdk doc upgrade

---

docs/user-guide/logs/manage-pipelines.md
docs/user-guide/logs/pipeline-config.md
docs/user-guide/logs/quick-start.md
docs/user-guide/logs/write-logs.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/manage-pipelines.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/pipeline-config.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/quick-start.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/write-logs.md

As the title suggests.
close #1559 #1561

docs: update docs about tag, inverted index and simple extract processor

---

i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/data-types.md

refer to: https://github.com/GreptimeTeam/docs/pull/1544

chore: the localize doc for `Datetime`

---

blog/release-0-13-0.md

docs: release v0.13.0

---

docs/user-guide/migrate-to-greptimedb/overview.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/migrate-to-greptimedb/overview.md
i18n/zh/docusaurus-plugin-content-docs/version-0.13/user-guide/migrate-to-greptimedb/overview.md
sidebars.ts
versioned_docs/version-0.13/user-guide/migrate-to-greptimedb/overview.md
versioned_sidebars/version-0.13-sidebars.json

chore: add overview to migration docs

---

docs/faq-and-others/faq.md
docs/user-guide/concepts/features-that-you-concern.md
docs/user-guide/concepts/why-greptimedb.md
i18n/zh/docusaurus-plugin-content-docs/current/faq-and-others/faq.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/concepts/features-that-you-concern.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/concepts/why-greptimedb.md
i18n/zh/docusaurus-plugin-content-docs/version-0.13/faq-and-others/faq.md
i18n/zh/docusaurus-plugin-content-docs/version-0.13/user-guide/concepts/features-that-you-concern.md
i18n/zh/docusaurus-plugin-content-docs/version-0.13/user-guide/concepts/why-greptimedb.md
versioned_docs/version-0.13/faq-and-others/faq.md
versioned_docs/version-0.13/user-guide/concepts/features-that-you-concern.md
versioned_docs/version-0.13/user-guide/concepts/why-greptimedb.md

docs: update benchmark reports

---

docs/user-guide/protocols/http.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/protocols/http.md

Close #1374 
Add doc for `/v1/sql/parse` API.

docs: sql parse

---

docs/user-guide/ingest-data/for-observability/overview.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/ingest-data/for-observability/overview.md
i18n/zh/docusaurus-plugin-content-docs/version-0.13/user-guide/ingest-data/for-observability/overview.md
versioned_docs/version-0.13/user-guide/ingest-data/for-observability/overview.md

chore: link to log doc from the ingesting data doc

---

blog/release-0-11-2.md

fix: correct release date

---

i18n/zh/docusaurus-plugin-content-docs/version-0.13/user-guide/administration/design-table.md
i18n/zh/docusaurus-plugin-content-docs/version-0.13/user-guide/concepts/data-model.md
versioned_docs/version-0.13/user-guide/administration/design-table.md
versioned_docs/version-0.13/user-guide/concepts/data-model.md

Update 0.13 data model and table design docs to the latest.

docs: update 0.13 data model design docs

---

docs/user-guide/ingest-data/for-iot/grpc-sdks/go.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/ingest-data/for-iot/grpc-sdks/go.md
i18n/zh/docusaurus-plugin-content-docs/version-0.13/user-guide/ingest-data/for-iot/grpc-sdks/go.md
variables/variables-0.13.ts
variables/variables-nightly.ts
versioned_docs/version-0.13/user-guide/ingest-data/for-iot/grpc-sdks/go.md

feat: bump go sdk to v0.6.1

---

sidebars.ts
versioned_sidebars/version-0.10-sidebars.json
versioned_sidebars/version-0.11-sidebars.json
versioned_sidebars/version-0.12-sidebars.json
versioned_sidebars/version-0.13-sidebars.json
versioned_sidebars/version-0.9-sidebars.json

fix: add procedure-info.md to sidebar

---

docs/reference/sql/range.md
versioned_docs/version-0.13/reference/sql/range.md

fix: links in range reference

---

docs/user-guide/logs/manage-pipelines.md

Added how to query pipeline through HTTP interface. Once https://github.com/GreptimeTeam/greptimedb/pull/5819 was merged, this could be merged too.

docs(pipeline): update query pipeline description

---

docs/user-guide/logs/pipeline-config.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/pipeline-config.md
i18n/zh/docusaurus-plugin-content-docs/version-0.13/user-guide/logs/pipeline-config.md
versioned_docs/version-0.13/user-guide/logs/pipeline-config.md

As the title suggests, add `json_parse` processor docs.

docs: add `json_parse` processor

---

docs/user-guide/deployments/deploy-on-kubernetes/configure-frontend-groups.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/deploy-on-kubernetes/configure-frontend-groups.md
i18n/zh/docusaurus-plugin-content-docs/version-0.13/user-guide/deployments/deploy-on-kubernetes/configure-frontend-groups.md
versioned_docs/version-0.13/user-guide/deployments/deploy-on-kubernetes/configure-frontend-groups.md

feat: update operator version

---

docs/user-guide/ingest-data/for-iot/grpc-sdks/java.md
docs/user-guide/ingest-data/for-iot/grpc-sdks/template.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/ingest-data/for-iot/grpc-sdks/java.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/ingest-data/for-iot/grpc-sdks/template.md

docs: explain connection exceptions in java sdk

---

docs/reference/sql/functions/overview.md
docs/user-guide/logs/query-logs.md
docs/user-guide/logs/quick-start.md
docs/user-guide/overview.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/functions/overview.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/query-logs.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/quick-start.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/overview.md

close https://github.com/GreptimeTeam/docs/issues/1626

docs: rewrite the log user guide with `matches_term`

---

docs/user-guide/protocols/http.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/protocols/http.md

closes #1480
add docs for http headers.

docs: add docs for auth headers

---

docs/reference/sql/alter.md
docs/reference/sql/create.md
docs/user-guide/logs/fulltext-index-config.md
docs/user-guide/logs/overview.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/alter.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/create.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/fulltext-index-config.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/overview.md
sidebars.ts

docs: fulltext backend config

---

docs/contributor-guide/overview.md
i18n/zh/docusaurus-plugin-content-docs/current/contributor-guide/overview.md
i18n/zh/docusaurus-plugin-content-docs/version-0.14/contributor-guide/overview.md
versioned_docs/version-0.14/contributor-guide/overview.md

docs: add deepwiki to contributor guide overview

---

blog/release-0-14-1.md

docs: release note v0.14.1

---

docs/user-guide/migrate-to-greptimedb/migrate-from-mysql.md
docs/user-guide/migrate-to-greptimedb/migrate-from-postgresql.md

* Adds data modeling and index documents links
* Remove tag column descriptions.

feat: improve migrate from mysql/pg documents

---

docs/db-cloud-shared/migrate/_migrate-from-prometheus.md
docs/db-cloud-shared/migrate/migrate-from-influxdb.md
docs/user-guide/migrate-to-greptimedb/migrate-from-clickhouse.md
docs/user-guide/migrate-to-greptimedb/migrate-from-influxdb.md
docs/user-guide/migrate-to-greptimedb/migrate-from-mysql.md
docs/user-guide/migrate-to-greptimedb/migrate-from-postgresql.md
docs/user-guide/migrate-to-greptimedb/migrate-from-prometheus.md
sidebars.ts

Close #1445 
Adds migrating from ClickHouse document.

docs: add migrate from clickhouse to greptimedb doc

---

docs/getting-started/installation/greptimedb-standalone.md
docs/user-guide/administration/remote-wal/quick-start.md
i18n/zh/docusaurus-plugin-content-docs/current/getting-started/installation/greptimedb-standalone.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/administration/remote-wal/quick-start.md
i18n/zh/docusaurus-plugin-content-docs/version-0.14/getting-started/installation/greptimedb-standalone.md
i18n/zh/docusaurus-plugin-content-docs/version-0.14/user-guide/administration/remote-wal/quick-start.md
versioned_docs/version-0.14/getting-started/installation/greptimedb-standalone.md
versioned_docs/version-0.14/user-guide/administration/remote-wal/quick-start.md

Fixed docker commands after #1633

fix: docker commands

---

i18n/zh/docusaurus-plugin-content-docs/version-0.14/user-guide/ingest-data/for-observability/opentelemetry.md
versioned_docs/version-0.14/user-guide/ingest-data/for-observability/opentelemetry.md

fix: trace table name

---

docs/user-guide/ingest-data/for-observability/alloy.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/ingest-data/for-observability/alloy.md
i18n/zh/docusaurus-plugin-content-docs/version-0.11/user-guide/ingest-data/for-observability/alloy.md
i18n/zh/docusaurus-plugin-content-docs/version-0.12/user-guide/ingest-data/for-observability/alloy.md
i18n/zh/docusaurus-plugin-content-docs/version-0.13/user-guide/ingest-data/for-observability/alloy.md
i18n/zh/docusaurus-plugin-content-docs/version-0.14/user-guide/ingest-data/for-observability/alloy.md
versioned_docs/version-0.11/user-guide/ingest-data/for-observability/alloy.md
versioned_docs/version-0.12/user-guide/ingest-data/for-observability/alloy.md
versioned_docs/version-0.13/user-guide/ingest-data/for-observability/alloy.md
versioned_docs/version-0.14/user-guide/ingest-data/for-observability/alloy.md

docs: fix typo in alloy docs

---

docs/user-guide/logs/pipeline-config.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/pipeline-config.md

close #1701 
This PR adds docs for auto-transform

docs: add docs for auto transform

---

i18n/zh/docusaurus-plugin-content-docs/current/getting-started/quick-start.md
i18n/zh/docusaurus-plugin-content-docs/version-0.10/getting-started/quick-start.md
i18n/zh/docusaurus-plugin-content-docs/version-0.11/getting-started/quick-start.md
i18n/zh/docusaurus-plugin-content-docs/version-0.12/getting-started/quick-start.md
i18n/zh/docusaurus-plugin-content-docs/version-0.13/getting-started/quick-start.md
i18n/zh/docusaurus-plugin-content-docs/version-0.14/getting-started/quick-start.md
i18n/zh/docusaurus-plugin-content-docs/version-0.9/getting-started/quick-start.md

fix: typos

---

docs/user-guide/logs/quick-start.md
docs/user-guide/protocols/http.md
docs/user-guide/traces/read-write.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/quick-start.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/protocols/http.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/traces/read-write.md
i18n/zh/docusaurus-plugin-content-docs/version-0.14/user-guide/logs/quick-start.md
i18n/zh/docusaurus-plugin-content-docs/version-0.14/user-guide/protocols/http.md
i18n/zh/docusaurus-plugin-content-docs/version-0.14/user-guide/traces/read-write.md
versioned_docs/version-0.14/user-guide/logs/quick-start.md
versioned_docs/version-0.14/user-guide/protocols/http.md
versioned_docs/version-0.14/user-guide/traces/read-write.md

* Use `custom_pipeline_logs` as table name for custom pipeline example.
* Adds authentication for traces and logs ingestion guide.

docs: add authentication for logs and traces ingestion

---

docusaurus.config.ts
package.json
pnpm-lock.yaml

chore: add Github discussion link to the AI footer text

---

docs/user-guide/deployments/configuration.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/configuration.md

close #1681
add `allow_region_failover_on_local_wal` configuration option

docs: add `allow_region_failover_on_local_wal` configuration option

---

docs/user-guide/administration/manage-data/region-failover.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/administration/manage-data/region-failover.md

add local WAL support details for region failover

docs: add local WAL support details for region failover

---

docusaurus.config.ts

chore: use description as twtter:description

---

docs/user-guide/query-data/promql.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/query-data/promql.md

docs: document limitation of promql selector

---

docs/getting-started/quick-start.md
i18n/zh/docusaurus-plugin-content-docs/current/getting-started/quick-start.md
i18n/zh/docusaurus-plugin-content-docs/version-0.14/getting-started/quick-start.md
versioned_docs/version-0.14/getting-started/quick-start.md

Improve the quick start:
* Remove the tag column concepts
* Add indexes
* Adds searching logs SQL
* Notes for schemaless.

docs: tweak quick start

---

docusaurus.config.ts
package-lock.json

style: AI text for i18n

---

docs/user-guide/flow-computation/manage-flow.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/flow-computation/manage-flow.md
i18n/zh/docusaurus-plugin-content-docs/version-0.14/user-guide/flow-computation/manage-flow.md
versioned_docs/version-0.14/user-guide/flow-computation/manage-flow.md

fix(docs): correct broken anchor links in flow computation guide

---

i18n/zh/docusaurus-plugin-content-docs/version-0.14/user-guide/integrations/grafana.md
versioned_docs/version-0.14/user-guide/integrations/grafana.md

docs: grafana plugin

---

docs/user-guide/logs/pipeline-config.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/pipeline-config.md
i18n/zh/docusaurus-plugin-content-docs/version-0.14/user-guide/logs/pipeline-config.md
versioned_docs/version-0.14/user-guide/logs/pipeline-config.md

* Add documentation explaining how to select the whole line in a processor or transformer when the input data type is text/plain.

chore: Add documentation explaining how to select the whole line in a processor or transformer when the input data type is text/plain

---

docs/reference/sql/copy.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/copy.md
i18n/zh/docusaurus-plugin-content-docs/version-0.14/reference/sql/copy.md
versioned_docs/version-0.14/reference/sql/copy.md

docs: notes on copying from CSV

---

docs/reference/sql/alter.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/alter.md
i18n/zh/docusaurus-plugin-content-docs/version-0.14/reference/sql/alter.md
versioned_docs/version-0.14/reference/sql/alter.md

Fixed the inconsistent titles in alert doc.

fix: titles in alter

---

docs/user-guide/logs/quick-start.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/quick-start.md
i18n/zh/docusaurus-plugin-content-docs/version-0.14/user-guide/logs/quick-start.md
versioned_docs/version-0.14/user-guide/logs/quick-start.md

refactor: move unstructured logs to lower priority

---

docs/user-guide/deployments/deploy-on-kubernetes/configure-frontend-groups.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/deploy-on-kubernetes/configure-frontend-groups.md
i18n/zh/docusaurus-plugin-content-docs/version-0.12/user-guide/deployments/deploy-on-kubernetes/configure-frontend-groups.md
i18n/zh/docusaurus-plugin-content-docs/version-0.13/user-guide/deployments/deploy-on-kubernetes/configure-frontend-groups.md
i18n/zh/docusaurus-plugin-content-docs/version-0.14/user-guide/deployments/deploy-on-kubernetes/configure-frontend-groups.md
versioned_docs/version-0.12/user-guide/deployments/deploy-on-kubernetes/configure-frontend-groups.md
versioned_docs/version-0.13/user-guide/deployments/deploy-on-kubernetes/configure-frontend-groups.md
versioned_docs/version-0.14/user-guide/deployments/deploy-on-kubernetes/configure-frontend-groups.md

related to: https://github.com/GreptimeTeam/helm-charts/pull/278

chore: rename frontends to frontendGroups in crd structure

---

docs/user-guide/administration/disaster-recovery/back-up-&-restore-meta-data.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/administration/disaster-recovery/back-up-&-restore-meta-data.md
sidebars.ts

* add doc for meta snapshot restore

chore: add doc for meta snapshot restore

---

docs/user-guide/deployments/deploy-on-kubernetes/common-helm-chart-configurations.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/deploy-on-kubernetes/common-helm-chart-configurations.md

Add docs for configuring metasrv backend storage by helm chart

docs: add docs for configuring metasrv backend storage by helm chart

---

docs/user-guide/integrations/telegraf.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/integrations/telegraf.md
i18n/zh/docusaurus-plugin-content-docs/version-0.14/user-guide/integrations/telegraf.md
sidebars.ts
versioned_docs/version-0.14/user-guide/integrations/telegraf.md
versioned_sidebars/version-0.14-sidebars.json

docs: add telegraf to integrations

---

docs/user-guide/administration/manage-metadata/manage-etcd.md
docs/user-guide/administration/remote-wal/cluster-deployment.md
docs/user-guide/deployments/deploy-on-kubernetes/common-helm-chart-configurations.md
docs/user-guide/deployments/deploy-on-kubernetes/configure-frontend-groups.md
docs/user-guide/deployments/deploy-on-kubernetes/monitoring/cluster-monitoring-deployment.md
i18n/zh/docusaurus-plugin-content-docs/current/enterprise/deployments/deploy-on-kubernetes/installation.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/administration/manage-metadata/manage-etcd.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/administration/remote-wal/cluster-deployment.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/deploy-on-kubernetes/common-helm-chart-configurations.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/deploy-on-kubernetes/configure-frontend-groups.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/deploy-on-kubernetes/monitoring/cluster-monitoring-deployment.md
i18n/zh/docusaurus-plugin-content-docs/version-0.14/enterprise/deployments/deploy-on-kubernetes/installation.md
i18n/zh/docusaurus-plugin-content-docs/version-0.14/user-guide/administration/manage-etcd.md
i18n/zh/docusaurus-plugin-content-docs/version-0.14/user-guide/administration/remote-wal/cluster-deployment.md
i18n/zh/docusaurus-plugin-content-docs/version-0.14/user-guide/deployments/deploy-on-kubernetes/configure-frontend-groups.md
i18n/zh/docusaurus-plugin-content-docs/version-0.14/user-guide/deployments/deploy-on-kubernetes/monitoring/cluster-monitoring-deployment.md
versioned_docs/version-0.14/user-guide/administration/manage-etcd.md
versioned_docs/version-0.14/user-guide/administration/remote-wal/cluster-deployment.md
versioned_docs/version-0.14/user-guide/deployments/deploy-on-kubernetes/configure-frontend-groups.md
versioned_docs/version-0.14/user-guide/deployments/deploy-on-kubernetes/monitoring/cluster-monitoring-deployment.md

refactor etcdEndpoints -> endpoints in meta backendStorage
Only update the documentation for v0.14 and the nightly version.
related PR: https://github.com/GreptimeTeam/helm-charts/pull/283
https://github.com/GreptimeTeam/greptimedb-operator/pull/274

refactor: etcd endpoints

---

docs/user-guide/administration/disaster-recovery/back-up-&-restore-data.md
docs/user-guide/administration/disaster-recovery/back-up-&-restore-meta-data.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/administration/disaster-recovery/back-up-&-restore-data.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/administration/disaster-recovery/back-up-&-restore-meta-data.md

chore: update cli

---

docs/user-guide/deployments/configuration.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/configuration.md

docs: metasrv config update

---

docusaurus.config.ts

fix: AI text

---

docs/user-guide/query-data/jaeger.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/query-data/jaeger.md

Add the configs about using jaeger-ui.

refactor: add the configs about using jaeger-ui

---

docs/user-guide/deployments-administration/disaster-recovery/back-up-&-restore-meta-data.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments-administration/disaster-recovery/back-up-&-restore-meta-data.md
i18n/zh/docusaurus-plugin-content-docs/version-0.14/user-guide/administration/disaster-recovery/back-up-&-restore-data.md
versioned_docs/version-0.14/user-guide/administration/disaster-recovery/back-up-&-restore-data.md

* update meta snapshot command doc
* add note for original import export doc
After discussing it with @WenyXu , the command line tool was reorganized again. The [previous one](https://github.com/GreptimeTeam/docs/pull/1825) was outdated.

chore: update meta command doc and add note for original command

---

blog/release-0-12-1.md

docs: add 0.12.1 release note

---

i18n/zh/docusaurus-plugin-content-docs/current/enterprise/deployments/monitoring/key-logs.md
i18n/zh/docusaurus-plugin-content-docs/current/enterprise/deployments/monitoring/key-metrics.md

Updates key logs:
- compaction logs
- license log
Updates key metrics:
- HTTP codes
- Mito write rows

docs: update key logs and key metrics

---

docs/user-guide/logs/pipeline-config.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/pipeline-config.md

close #1852 
This PR adds the docs for the pipeline doc version 2 and its changes regarding the transform process.

docs: add docs for pipeline version 2

---

docs/user-guide/protocols/http.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/protocols/http.md

…guide
For https://github.com/GreptimeTeam/greptimedb/pull/6384
* Adds `csvWithNames` and `csvWithNamesAndTypes` format to http user guide.

docs: add csvWithNames and csvWithNamesAndTypes formats t

---

docs/user-guide/deployments-administration/disaster-recovery/back-up-&-restore-meta-data.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments-administration/disaster-recovery/back-up-&-restore-meta-data.md

add MySQL backend example for metadata backup and restore

docs: add MySQL backend example for metadata backup and restore

---

docs/user-guide/deployments-administration/deploy-on-kubernetes/common-helm-chart-configurations.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments-administration/deploy-on-kubernetes/common-helm-chart-configurations.md
i18n/zh/docusaurus-plugin-content-docs/version-0.11/user-guide/deployments/deploy-on-kubernetes/common-helm-chart-configurations.md
i18n/zh/docusaurus-plugin-content-docs/version-0.12/user-guide/deployments/deploy-on-kubernetes/common-helm-chart-configurations.md
i18n/zh/docusaurus-plugin-content-docs/version-0.13/user-guide/deployments/deploy-on-kubernetes/common-helm-chart-configurations.md
i18n/zh/docusaurus-plugin-content-docs/version-0.14/user-guide/deployments/deploy-on-kubernetes/common-helm-chart-configurations.md
versioned_docs/version-0.11/user-guide/deployments/deploy-on-kubernetes/common-helm-chart-configurations.md
versioned_docs/version-0.12/user-guide/deployments/deploy-on-kubernetes/common-helm-chart-configurations.md
versioned_docs/version-0.13/user-guide/deployments/deploy-on-kubernetes/common-helm-chart-configurations.md
versioned_docs/version-0.14/user-guide/deployments/deploy-on-kubernetes/common-helm-chart-configurations.md

correct service role in helm chart configuration examples

fix: correct service role in helm chart configuration examples

---

docs/user-guide/deployments-administration/wal/remote-wal/manage-kafka.md

fix indentation in manage-kafka.md

chore: fix indentation in manage-kafka.md

---

versioned_docs/version-0.11/user-guide/protocols/http.md
versioned_docs/version-0.12/user-guide/protocols/http.md
versioned_docs/version-0.13/user-guide/protocols/http.md
versioned_docs/version-0.14/user-guide/protocols/http.md

fix: conf links

---

i18n/zh/docusaurus-plugin-content-docs/version-0.11/user-guide/deployments/configuration.md
i18n/zh/docusaurus-plugin-content-docs/version-0.11/user-guide/protocols/http.md
i18n/zh/docusaurus-plugin-content-docs/version-0.12/user-guide/deployments/configuration.md
i18n/zh/docusaurus-plugin-content-docs/version-0.12/user-guide/protocols/http.md
i18n/zh/docusaurus-plugin-content-docs/version-0.13/user-guide/deployments/configuration.md
i18n/zh/docusaurus-plugin-content-docs/version-0.13/user-guide/protocols/http.md
i18n/zh/docusaurus-plugin-content-docs/version-0.14/user-guide/deployments/configuration.md
i18n/zh/docusaurus-plugin-content-docs/version-0.14/user-guide/protocols/http.md
versioned_docs/version-0.11/user-guide/deployments/configuration.md
versioned_docs/version-0.12/user-guide/deployments/configuration.md
versioned_docs/version-0.13/user-guide/deployments/configuration.md
versioned_docs/version-0.14/user-guide/deployments/configuration.md

fix: links

---

sidebars.ts

- Updated `sidebars.ts` to include the new 'process-list' entry under the SQL information schema section.
Add 'process-list' to SQL information schema in `sidebars.ts`
- Updated `sidebars.ts` to include the new 'process-list' entry under the SQL information schema section.

fix: add processlist to sidebar

---

docs/user-guide/logs/quick-start.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/quick-start.md
i18n/zh/docusaurus-plugin-content-docs/version-0.15/user-guide/logs/quick-start.md
versioned_docs/version-0.15/user-guide/logs/quick-start.md

* fix greptime_identity link error

chore: fix greptime_identity link error

---

docs/user-guide/logs/write-logs.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/write-logs.md

* add doc for pipeline skip error

chore: add doc for pipeline skip error

---

docs/enterprise/overview.md
i18n/zh/docusaurus-plugin-content-docs/current/enterprise/overview.md
i18n/zh/docusaurus-plugin-content-docs/version-0.15/enterprise/overview.md
versioned_docs/version-0.15/enterprise/overview.md

Update enterprise/overview to include more features introduced in 25.05

docs: more enterprise feature listing

---

variables/variables-0.15.ts
variables/variables-nightly.ts

chore: update ingester version

---

docs/user-guide/ingest-data/for-iot/grpc-sdks/go.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/ingest-data/for-iot/grpc-sdks/go.md
i18n/zh/docusaurus-plugin-content-docs/version-0.11/user-guide/ingest-data/for-iot/grpc-sdks/go.md
i18n/zh/docusaurus-plugin-content-docs/version-0.12/user-guide/ingest-data/for-iot/grpc-sdks/go.md
i18n/zh/docusaurus-plugin-content-docs/version-0.13/user-guide/ingest-data/for-iot/grpc-sdks/go.md
i18n/zh/docusaurus-plugin-content-docs/version-0.14/user-guide/ingest-data/for-iot/grpc-sdks/go.md
i18n/zh/docusaurus-plugin-content-docs/version-0.15/user-guide/ingest-data/for-iot/grpc-sdks/go.md
versioned_docs/version-0.11/user-guide/ingest-data/for-iot/grpc-sdks/go.md
versioned_docs/version-0.12/user-guide/ingest-data/for-iot/grpc-sdks/go.md
versioned_docs/version-0.13/user-guide/ingest-data/for-iot/grpc-sdks/go.md
versioned_docs/version-0.14/user-guide/ingest-data/for-iot/grpc-sdks/go.md
versioned_docs/version-0.15/user-guide/ingest-data/for-iot/grpc-sdks/go.md

- `c.client.Write` -> `cli.Write`, the client variable is `cli`:
```
cli, _ := greptime.NewClient(cfg)
```
- add close client example

fix: go sdk client usage

---

docs/user-guide/deployments-administration/deploy-on-kubernetes/overview.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments-administration/deploy-on-kubernetes/overview.md
i18n/zh/docusaurus-plugin-content-docs/version-0.15/user-guide/deployments-administration/deploy-on-kubernetes/overview.md
versioned_docs/version-0.15/user-guide/deployments-administration/deploy-on-kubernetes/overview.md

chore: add cloud service support

---

docs/user-guide/logs/pipeline-config.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/pipeline-config.md

* deprecated json-path processor

chore: deprecated json-path

---

blog/release-0-15-0.md
blog/release-0-15-2.md

also mention dashboard changes in 0.15.0 release note
- add 0.15.2 release note
- also mention dashboard changes in 0.15.0 release note

docs: add 0.15.2 release note

---

docs/greptimecloud/integrations/otlp.md
i18n/zh/docusaurus-plugin-content-docs/current/greptimecloud/integrations/otlp.md
i18n/zh/docusaurus-plugin-content-docs/version-0.15/greptimecloud/integrations/otlp.md
versioned_docs/version-0.15/greptimecloud/integrations/otlp.md

chore: emphasize HTTP/protobuf for OTLP

---

docs/greptimecloud/integrations/otlp.md
i18n/zh/docusaurus-plugin-content-docs/current/greptimecloud/integrations/otlp.md
i18n/zh/docusaurus-plugin-content-docs/version-0.15/greptimecloud/integrations/otlp.md
versioned_docs/version-0.15/greptimecloud/integrations/otlp.md

fix: duplicate basic

---

docs/enterprise/deployments-administration/monitoring/check-db-status.md
docs/enterprise/deployments-administration/monitoring/overview.md
docs/reference/http-endpoints.md
docs/user-guide/protocols/http.md
i18n/zh/docusaurus-plugin-content-docs/current/enterprise/deployments-administration/monitoring/check-db-status.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/http-endpoints.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/protocols/http.md

chore: check db status

---

docs/user-guide/logs/pipeline-config.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/pipeline-config.md

close #1934 
This PR adds docs for the filter processor.

docs: add docs for filter processor

---

docs/reference/sql/information-schema/region-statistics.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/information-schema/region-statistics.md

closes #1947
Add `sst_num` field to `region_statistics` table

docs: add sst_num to region_statistics

---

.github/workflows/bump-patch-version.yml

Avoid to commit `package-lock.json`.

fix: only commit ts files

---

blog/release-0-15-3.md

docs: add v0.15.3 changelog

---

docs/reference/sql/create.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/create.md

Close #1941 
* Adds db options references.
* Adds table option.

feat: adds table and db options

---

docs/user-guide/deployments-administration/manage-data/table-sharding.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments-administration/manage-data/table-sharding.md
i18n/zh/docusaurus-plugin-content-docs/version-0.15/user-guide/deployments-administration/manage-data/table-sharding.md
versioned_docs/version-0.15/user-guide/deployments-administration/manage-data/table-sharding.md

fix: update table partition example

---

docs/user-guide/logs/write-logs.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/write-logs.md

* add doc for flatten_json_object
Waiting for this pr to merge, I'll sync to the docs to version 0.15.

chore: add doc for flatten_json_object

---

blog/release-0-16-0.md

docs: release note v0.16.0

---

docs/reference/sql/functions/overview.md
docs/reference/sql/overview.md
docusaurus.config.ts
i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/functions/overview.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/overview.md
i18n/zh/docusaurus-plugin-content-docs/version-0.12/reference/sql/functions/overview.md
i18n/zh/docusaurus-plugin-content-docs/version-0.12/reference/sql/overview.md
i18n/zh/docusaurus-plugin-content-docs/version-0.13/reference/sql/functions/overview.md
i18n/zh/docusaurus-plugin-content-docs/version-0.13/reference/sql/overview.md
i18n/zh/docusaurus-plugin-content-docs/version-0.14/reference/sql/functions/overview.md
i18n/zh/docusaurus-plugin-content-docs/version-0.14/reference/sql/overview.md
i18n/zh/docusaurus-plugin-content-docs/version-0.15/reference/sql/functions/overview.md
i18n/zh/docusaurus-plugin-content-docs/version-0.15/reference/sql/overview.md
i18n/zh/docusaurus-plugin-content-docs/version-0.16/reference/sql/functions/overview.md
i18n/zh/docusaurus-plugin-content-docs/version-0.16/reference/sql/overview.md
versioned_docs/version-0.12/reference/sql/functions/overview.md
versioned_docs/version-0.12/reference/sql/overview.md
versioned_docs/version-0.13/reference/sql/functions/overview.md
versioned_docs/version-0.13/reference/sql/overview.md
versioned_docs/version-0.14/reference/sql/functions/overview.md
versioned_docs/version-0.14/reference/sql/overview.md
versioned_docs/version-0.15/reference/sql/functions/overview.md
versioned_docs/version-0.15/reference/sql/overview.md
versioned_docs/version-0.16/reference/sql/functions/overview.md
versioned_docs/version-0.16/reference/sql/overview.md

enable trailing slash to keep same url with cloudflare
may be good for search index.

feat: enable trailingSlash

---

blog/release-0-16-0.md

docs: refine highlights in v0.16.0 release note

---

blog/release-0-16-0.md

docs: add dashbaord release note

---

blog/release-0-16-0.md

chore: add breaking change info

---

docs/user-guide/deployments-administration/manage-data/table-sharding.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments-administration/manage-data/table-sharding.md
i18n/zh/docusaurus-plugin-content-docs/version-0.15/user-guide/deployments-administration/manage-data/table-sharding.md
i18n/zh/docusaurus-plugin-content-docs/version-0.16/user-guide/deployments-administration/manage-data/table-sharding.md
versioned_docs/version-0.15/user-guide/deployments-administration/manage-data/table-sharding.md
versioned_docs/version-0.16/user-guide/deployments-administration/manage-data/table-sharding.md

fix: typo in partition rule

---

docs/reference/sql/functions/vector.md
versioned_docs/version-0.15/reference/sql/functions/vector.md
versioned_docs/version-0.16/reference/sql/functions/vector.md

fix: align the heading with func name for vector cos/dot_product

---

i18n/zh/docusaurus-plugin-content-docs/current.json
i18n/zh/docusaurus-plugin-content-docs/version-0.16.json

chore: ZH navigation translation

---

docs/enterprise/read-replica.md
i18n/zh/docusaurus-plugin-content-docs/current/enterprise/read-replica.md

docs: minor clarify for read-replica 

---

docs/user-guide/deployments-administration/manage-metadata/configuration.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments-administration/manage-metadata/configuration.md
i18n/zh/docusaurus-plugin-content-docs/version-0.16/user-guide/deployments-administration/manage-metadata/configuration.md
versioned_docs/version-0.16/user-guide/deployments-administration/manage-metadata/configuration.md

chore: add more description for metadata config

---

docs/user-guide/ingest-data/for-observability/prometheus.md
docs/user-guide/ingest-data/for-observability/vector.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/ingest-data/for-observability/prometheus.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/ingest-data/for-observability/vector.md
i18n/zh/docusaurus-plugin-content-docs/version-0.16/enterprise/read-replica.md
i18n/zh/docusaurus-plugin-content-docs/version-0.16/user-guide/ingest-data/for-observability/prometheus.md
i18n/zh/docusaurus-plugin-content-docs/version-0.16/user-guide/ingest-data/for-observability/vector.md
versioned_docs/version-0.16/enterprise/read-replica.md
versioned_docs/version-0.16/user-guide/ingest-data/for-observability/prometheus.md
versioned_docs/version-0.16/user-guide/ingest-data/for-observability/vector.md

chore: add vector docs

---

docs/reference/sql/information-schema/tables.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/information-schema/tables.md
i18n/zh/docusaurus-plugin-content-docs/version-0.16/reference/sql/information-schema/tables.md
versioned_docs/version-0.16/reference/sql/information-schema/tables.md

chore: table size description

---

docs/reference/sql/admin.md
docs/user-guide/deployments-administration/maintenance/table-reconciliation.md
docs/user-guide/deployments-administration/manage-metadata/restore-backup.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/admin.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments-administration/maintenance/table-reconciliation.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments-administration/manage-metadata/restore-backup.md
sidebars.ts

close #1993
This PR introduces documentation for table reconciliation mechanism, which helps detect and repair metadata inconsistencies between Metasrv and Datanode in distributed environments.

feat: add table reconciliation feature documentation and admin functions

---

docs/user-guide/deployments-administration/configuration.md
i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments-administration/configuration.md
i18n/zh/docusaurus-plugin-content-docs/version-0.16/user-guide/deployments-administration/configuration.md
versioned_docs/version-0.16/user-guide/deployments-administration/configuration.md

chore: link configurations

---

docs/reference/sql/information-schema/partitions.md
i18n/zh/docusaurus-plugin-content-docs/current/getting-started/quick-start.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/information-schema/partitions.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/select.md

fix: all mysql style comments

---

blog/release-0-17-0.md

docs: refine highlights

---

i18n/zh/docusaurus-plugin-content-docs/current/user-guide/concepts/why-greptimedb.md
i18n/zh/docusaurus-plugin-content-docs/version-0.14/user-guide/concepts/why-greptimedb.md
i18n/zh/docusaurus-plugin-content-docs/version-0.15/user-guide/concepts/why-greptimedb.md
i18n/zh/docusaurus-plugin-content-docs/version-0.16/user-guide/concepts/why-greptimedb.md
i18n/zh/docusaurus-plugin-content-docs/version-0.17/user-guide/concepts/why-greptimedb.md

docs: fix typo

---

docs/enterprise/autopilot/region-balancer.md
i18n/zh/docusaurus-plugin-content-docs/current/enterprise/autopilot/region-balancer.md
i18n/zh/docusaurus-plugin-content-docs/version-0.12/enterprise/autopilot/region-balancer.md
i18n/zh/docusaurus-plugin-content-docs/version-0.13/enterprise/autopilot/region-balancer.md
i18n/zh/docusaurus-plugin-content-docs/version-0.14/enterprise/autopilot/region-balancer.md
i18n/zh/docusaurus-plugin-content-docs/version-0.15/enterprise/autopilot/region-balancer.md
i18n/zh/docusaurus-plugin-content-docs/version-0.16/enterprise/autopilot/region-balancer.md
i18n/zh/docusaurus-plugin-content-docs/version-0.17/enterprise/autopilot/region-balancer.md
versioned_docs/version-0.12/enterprise/autopilot/region-balancer.md
versioned_docs/version-0.13/enterprise/autopilot/region-balancer.md
versioned_docs/version-0.14/enterprise/autopilot/region-balancer.md
versioned_docs/version-0.15/enterprise/autopilot/region-balancer.md
versioned_docs/version-0.16/enterprise/autopilot/region-balancer.md
versioned_docs/version-0.17/enterprise/autopilot/region-balancer.md

docs: supplement region balancer configuration guide

---

blog/release-0-17-1.md

docs: add v0.17.1 release note

---

docs/getting-started/quick-start.md
i18n/zh/docusaurus-plugin-content-docs/current/getting-started/quick-start.md
i18n/zh/docusaurus-plugin-content-docs/version-0.17/getting-started/quick-start.md
versioned_docs/version-0.17/getting-started/quick-start.md

Improve the quick start guide by:
* adding appropriate sorting to ensure readable, stable results;
* adding PromQL examples and examples that combine PromQL with SQL.

docs: improve quick start

---

blog/release-0-17-2.md

docs: release note for v0.17.2

---

blog/release-0-17-2.md

Updated the header format for the v0.17.2 release note.

fix: Change header from '0.17.2' to 'v0.17.2'

---

i18n/zh/docusaurus-plugin-content-docs/version-0.17/user-guide/deployments-administration/deploy-on-kubernetes/deploy-greptimedb-cluster.md
i18n/zh/docusaurus-plugin-content-docs/version-0.17/user-guide/deployments-administration/monitoring/cluster-monitoring-deployment.md
i18n/zh/docusaurus-plugin-content-docs/version-0.17/user-guide/deployments-administration/monitoring/monitor-cluster-with-prometheus.md
versioned_docs/version-0.17/user-guide/deployments-administration/deploy-on-kubernetes/deploy-greptimedb-cluster.md
versioned_docs/version-0.17/user-guide/deployments-administration/monitoring/cluster-monitoring-deployment.md
versioned_docs/version-0.17/user-guide/deployments-administration/monitoring/monitor-cluster-with-prometheus.md
versioned_sidebars/version-0.17-sidebars.json

chore: apply monitor refactor to v0.17
