- docs/developer-guide/overview.md
- docs/user-guide/reading-writing-data.md
- docs/user-guide/supported-protocols/http-api.md
- docs/user-guide/supported-protocols/prometheus.md
Main changes:
* Fixed typo in developer guide overview
* Fixed code block.
> docs: fix typo and format

- docs/reference/configuration.md
As https://github.com/GreptimeTeam/greptimedb/pull/545 was merged, we should change sample config items in docs accordingly, to be sepcific, for datanode and frontend config samples, rename `metasrv_addr` item in `meta_client_opts` section to `metasrv_addrs`, change type from string to string list.
> fix: metasrv addr in sample configs

- docs/developer-guide/get-started.md
Adds C/C++ toolchain to the list, changes the order of the dependencies, and updates the link of Rust to the official install guide.
> docs: Update list of build dependencies

- docs/reference/configuration.md
Remove datanode MySQL options in standalone mode, please merge when https://github.com/GreptimeTeam/greptimedb/pull/595 is merged.
> fix: remove mysql standalone

- docs/public/_headers
Steps To Reproduce:
- Create a new HTML file
- Put <iframe src="https://docs.greptime.com/"  frameborder="0"></iframe>
- Save the file in *.html format.
- Open that file in your browser.
> fix(global): add headers to protect against iframe injection

- docs/developer-guide/datanode/storage-engine.md
Changed `aregion` to `a region`
> docs: fix region typo in storage engine section

- docs/user-guide/supported-protocols/http-api.md
This pr mainly fixes the script handler doc on changing from `schema` to `db` in param
> fix: change schema to db in script handler

- docs/reference/configuration.md
This PR corrects outdated examples in the configuration section.
This fixes #210
> docs: Correct some examples of config file

- docs/user-guide/use-promql.md
Fix the title. Change from `Java SDK` to `Use PromQL`
> fix: correct use-promql title

- docs/reference/sql/create.md
- docs/user-guide/table-management.md
- Add table option reference to "Table Management" sections
- Add `write_buffer_size` table option docs.
Fix #229
> docs: add table options to table-management

- docs/developer-guide/how-to/how-to-write-sdk.md
> docs: update "How to write gRPC SDK for GreptimeDB"

- .github/workflows/node.js.yml
This action allows every contributor to see detailed error information about any build failure.
> ci: add github action as well to check build error

- docs/user-guide/authentication.md
This pr mainly removes `cargo run --` in authentication docs.
fix #282
> fix: remove `cargo` in docs

- docs/reference/data-types.md
As [feat: support timestamp precision on creating table #1332](https://github.com/GreptimeTeam/greptimedb/pull/1332) has been merged, we now supports specifying timestamp precision when creating table. 
fixes #295
> docs: add timestamp precision desc

- docs/developer-guide/meta/selector.md
> docs: change default selector in meta from "LeaseBased" to "LoadBased"

- docs/reference/sdk/java.md
- docs/user-guide/clients/grpc.md
* Add sample code to Java connection.
* `GreptimeDBOptions` is removed because users can find the latest information in API document.
> docs: add auth info to Java sdk

- docs/user-guide/prometheus.md
The valid `basic_auth` config is:
```
remote_write:
- url: http://localhost:5080/api/default/prometheus/api/v1/write
basic_auth:
username: greptime_user
password: greptime_password
```
But the doc has an unnessary `-` before `basic_auth`, making the whole configuration invalid.
And the database authentication is disabled by default, so I think the `basic_auth` should be commented by default too.
> fix: prometheus basic_auth config

- docs/user-guide/write-data/influxdb-line.md
In `Table Management`, there is an example of creating a `monitor` table. In the following `Write Data/SQL` section, there is an example of inserting data into the `monitor` table. On the other hand, in `Write Data/InfluxDB Line` section, there is an example of inserting data into the `system_metrics` table. I guess that users should read `Write Data/InfluxDB Line` after they read `Table Management`. I think this might confuse them. 
So, this PR replaces `system_metrics` with `monitor` so that users can immediately execute a insert command after reading `Table Management`.
In addition, this PR appends a `InfluxdDB Line protocol` reference in the `Write Data/InfluxDB Line` section so that users could easily understand about the `InfluxdDB Line protocol`.
> feat: improve influxdb line document

- docs/reference/sql/show.md
This PR adds an example of `SHOW ~ WHERE ~`.
Right now `greptimedb` supports this feature:
* https://github.com/GreptimeTeam/greptimedb/pull/1962
* https://github.com/GreptimeTeam/greptimedb/pull/1829
> feat: add where in show

- docs/reference/sql/select.md
- docs/summary.yml
- docs/user-guide/cookbook/overview.md
Add cookbook for commonly used cases including
- Query latest 5 minutes of data
- Group by time interval
- Cast number literal to timestamp
- Cast string literal to timestamp
- Extract the day of the year from timestamp
> feat: cookbook for commonly used cases

- docs/developer-guide/overview.md
It seems like `meta` link doesn't exist. So, this PR fixes the broken link.
> fix: broken link

- docs/getting-started/overview.md
- docs/zh/getting-started/overview.md
This [link](https://www.docker.com/getting-started/) for getting started with docker has moved to https://www.docker.com/get-started/ .
Then some links in the document use relative paths, but cannot be accessed normally in GitHub, so add '...` prefix.
> docs: fix error links

- docs/en/v0.4/reference/sql/create.md
- docs/en/v0.4/user-guide/query-external-data.md
- docs/zh/v0.4/reference/sql/create.md
- docs/zh/v0.4/user-guide/query-external-data.md
It seems incorrect with the `CREATE TABLE` and `CREATE EXTERNAL TABLE` syntax. Fix them and unify the formats between them.
> docs(create): fix incorrect syntax and unify format

- docs/en/v0.4/user-guide/operations/run-on-android.md
- docs/zh/v0.4/user-guide/operations/run-on-android.md
Change Termux download link from Google Play to Github release page.
> fix(user-guide): change termux download link to github release

- docs/en/v0.4/developer-guide/metasrv/admin-api.md
- docs/zh/v0.4/developer-guide/metasrv/admin-api.md
This pr mainly fix typo backquote -> single quote.
> docs: typo backquote -> single quote

- docs/en/v0.4/user-guide/operations/configuration.md
- docs/zh/v0.4/user-guide/operations/configuration.md
add WAL dir config in the doc.
See https://github.com/GreptimeTeam/greptimedb/pull/2606
Fixes #650
> docs: add wal dir config doc

- docs/en/v0.4/user-guide/operations/configuration.md
- docs/zh/v0.4/user-guide/operations/configuration.md
Update en and zh frontend cmd docs from grpc_addr to rpc_addr . Related change https://github.com/GreptimeTeam/greptimedb/pull/2609, https://github.com/GreptimeTeam/docs/issues/653
> docs: align frontend cmd name to rpc 

- docs/en/v0.4/db-cloud-shared/clients/grafana-integration.md
- docs/en/v0.4/db-cloud-shared/clients/otlp-integration.md
- docs/en/v0.4/db-cloud-shared/clients/vector-integration.md
- docs/en/v0.4/greptimecloud/integrations/influxdb.md
- docs/en/v0.4/greptimecloud/integrations/mysql.md
- docs/en/v0.4/greptimecloud/integrations/postgresql.md
- docs/en/v0.4/greptimecloud/integrations/prometheus/quick-setup.md
- docs/en/v0.4/greptimecloud/integrations/sdk-libraries/go.md
- docs/en/v0.4/greptimecloud/integrations/sdk-libraries/java.md
- docs/zh/v0.4/db-cloud-shared/clients/grafana-integration.md
- docs/zh/v0.4/db-cloud-shared/clients/otlp-integration.md
- docs/zh/v0.4/db-cloud-shared/clients/vector-integration.md
- docs/zh/v0.4/greptimecloud/integrations/influxdb.md
- docs/zh/v0.4/greptimecloud/integrations/mysql.md
- docs/zh/v0.4/greptimecloud/integrations/postgresql.md
- docs/zh/v0.4/greptimecloud/integrations/prometheus/quick-setup.md
- docs/zh/v0.4/greptimecloud/integrations/sdk-libraries/go.md
- docs/zh/v0.4/greptimecloud/integrations/sdk-libraries/java.md
This patch uses `<password>` placeholder in cloud integration docs.
> feat: use password placeholder for cloud integration docs

- docs/en/v0.3/db-cloud-shared/clients/otlp-integration.md
- docs/en/v0.4/db-cloud-shared/clients/otlp-integration.md
- docs/zh/v0.3/db-cloud-shared/clients/otlp-integration.md
- docs/zh/v0.4/db-cloud-shared/clients/otlp-integration.md
GreptimeDB is not a collector, it is a backend, or vendor.  GreptimeDB has not implemented the collector part.
- https://opentelemetry.io/ecosystem/vendors/
- https://opentelemetry.io/docs/collector/
> fix: remove OTLP collector description

- docs/v0.4/en/reference/sql/create.md
- docs/v0.4/en/user-guide/operations/configuration.md
> chore: add documentation for custom storage

- docs/v0.4/en/user-guide/operations/configuration.md
- docs/v0.4/zh/user-guide/operations/configuration.md
related: https://github.com/GreptimeTeam/greptimedb/pull/3003
> feat: make logging to stdout configurable

- docs/v0.4/en/getting-started/quick-start/prerequisites.md
- docs/v0.4/en/getting-started/quick-start/prometheus.md
- docs/v0.4/en/getting-started/quick-start/vector.md
- docs/v0.4/en/reference/sql/functions.md
- docs/v0.4/zh/getting-started/quick-start/prerequisites.md
- docs/v0.4/zh/getting-started/quick-start/prometheus.md
- docs/v0.4/zh/getting-started/quick-start/vector.md
- docs/v0.4/zh/reference/sql/functions.md
- docs/v0.5/en/getting-started/quick-start/prerequisites.md
- docs/v0.5/en/getting-started/quick-start/prometheus.md
- docs/v0.5/en/getting-started/quick-start/vector.md
- docs/v0.5/en/reference/sql/functions.md
- docs/v0.5/zh/getting-started/quick-start/prerequisites.md
- docs/v0.5/zh/getting-started/quick-start/prometheus.md
- docs/v0.5/zh/getting-started/quick-start/vector.md
- docs/v0.5/zh/reference/sql/functions.md
- Use grafana 9.5.15 in quick start
- The datafusion link of date functions
> fix: grafana version and the link of date functions

- docs/v0.6/en/greptimecloud/getting-started/go.md
- docs/v0.6/en/greptimecloud/getting-started/influxdb.md
- docs/v0.6/en/greptimecloud/getting-started/java.md
- docs/v0.6/en/greptimecloud/getting-started/mysql.md
- docs/v0.6/en/greptimecloud/getting-started/node.md
- docs/v0.6/en/greptimecloud/getting-started/python.md
- docs/v0.6/en/greptimecloud/getting-started/quick-start/go.md
- docs/v0.6/en/greptimecloud/getting-started/quick-start/influxdb.md
- docs/v0.6/en/greptimecloud/getting-started/quick-start/java.md
- docs/v0.6/en/greptimecloud/getting-started/quick-start/mysql.md
- docs/v0.6/en/greptimecloud/getting-started/quick-start/node.md
- docs/v0.6/en/greptimecloud/getting-started/quick-start/python.md
- docs/v0.6/en/greptimecloud/getting-started/quick-start/vector.md
- docs/v0.6/en/greptimecloud/getting-started/vector.md
- docs/v0.6/zh/greptimecloud/getting-started/go.md
- docs/v0.6/zh/greptimecloud/getting-started/influxdb.md
- docs/v0.6/zh/greptimecloud/getting-started/java.md
- docs/v0.6/zh/greptimecloud/getting-started/mysql.md
- docs/v0.6/zh/greptimecloud/getting-started/node.md
- docs/v0.6/zh/greptimecloud/getting-started/python.md
- docs/v0.6/zh/greptimecloud/getting-started/quick-start/go.md
- docs/v0.6/zh/greptimecloud/getting-started/quick-start/influxdb.md
- docs/v0.6/zh/greptimecloud/getting-started/quick-start/java.md
- docs/v0.6/zh/greptimecloud/getting-started/quick-start/mysql.md
- docs/v0.6/zh/greptimecloud/getting-started/quick-start/node.md
- docs/v0.6/zh/greptimecloud/getting-started/quick-start/python.md
- docs/v0.6/zh/greptimecloud/getting-started/quick-start/vector.md
- docs/v0.6/zh/greptimecloud/getting-started/vector.md
retrieve missing Quick Start documentation for GreptimeCloud
> fix: retrieve missing Quick Start documentation for GreptimeCloud

- docs/v0.6/en/greptimecloud/getting-started/quick-start/go.md
- docs/v0.6/en/greptimecloud/getting-started/quick-start/influxdb.md
- docs/v0.6/en/greptimecloud/getting-started/quick-start/java.md
- docs/v0.6/en/greptimecloud/getting-started/quick-start/node.md
- docs/v0.6/en/greptimecloud/getting-started/quick-start/python.md
- docs/v0.6/zh/greptimecloud/getting-started/quick-start/go.md
- docs/v0.6/zh/greptimecloud/getting-started/quick-start/influxdb.md
- docs/v0.6/zh/greptimecloud/getting-started/quick-start/java.md
- docs/v0.6/zh/greptimecloud/getting-started/quick-start/node.md
- docs/v0.6/zh/greptimecloud/getting-started/quick-start/python.md
Fix the quick start commands in GreptimeCloud
> fix: quick start command in GreptimeCloud

- docs/v0.6/en/user-guide/client-libraries/go.md
- docs/v0.6/en/user-guide/client-libraries/java.md
- docs/v0.6/en/user-guide/client-libraries/template.md
- docs/v0.6/zh/user-guide/client-libraries/go.md
- docs/v0.6/zh/user-guide/client-libraries/java.md
- docs/v0.6/zh/user-guide/client-libraries/template.md
Since each SDK supports two code object styles, the outline of the SDK documentation template needs to be changed.
**This change requires each SDK to support two styles of object creation code**, I'm not sure it is the best practice.
@killme2008 @fengjiachun @yuanbohan 
Before:
```
- Create data
- Insert data
- Update data
```
Now:
```
- Low-level API
- Create data
- Insert data
- Update data
-High-level API
- Create data
- Insert data
- Update data
```
> docs: new outline of SDK documentations

- docs/v0.7/en/reference/sql/range.md
- docs/v0.7/zh/reference/sql/range.md
update range query docs
- new fill behavior
- Range SQL structure
- `first_value`/`last_value` use `ts` as default `order by` 
related pr: https://github.com/GreptimeTeam/greptimedb/pull/3489
Closes https://github.com/GreptimeTeam/docs/issues/832
> docs: update range query docs

- docs/v0.7/en/contributor-guide/metasrv/admin-api.md
- docs/v0.7/zh/contributor-guide/metasrv/admin-api.md
Remove redundant metasrv API doc
> chore: remove redundant metasrv api

- docs/v0.6/en/reference/sql/copy.md
- docs/v0.6/zh/reference/sql/copy.md
- docs/v0.7/en/reference/sql/copy.md
- docs/v0.7/zh/reference/sql/copy.md
Add time range option doc for `COPY` statements.
Closes #857
> docs: copy database example

- docs/v0.4/en/user-guide/concepts/features-that-you-concern.md
- docs/v0.4/zh/user-guide/concepts/features-that-you-concern.md
- docs/v0.5/en/user-guide/concepts/features-that-you-concern.md
- docs/v0.5/zh/user-guide/concepts/features-that-you-concern.md
- docs/v0.6/en/user-guide/concepts/features-that-you-concern.md
- docs/v0.6/zh/user-guide/concepts/features-that-you-concern.md
- docs/v0.7/en/user-guide/concepts/features-that-you-concern.md
- docs/v0.7/zh/user-guide/concepts/features-that-you-concern.md
This PR removes global_ttl option related sections since this config item is no longer valid since v0.4
- closes #880
> docs: remove global ttl

- docs/v0.7/en/contributor-guide/metasrv/admin-api.md
- docs/v0.7/zh/contributor-guide/metasrv/admin-api.md
> docs: for metasrv maintenance endpoints

- docs/v0.7/en/reference/sql/create.md
- docs/v0.7/en/user-guide/operations/configuration.md
- docs/v0.7/zh/reference/sql/create.md
- docs/v0.7/zh/user-guide/operations/configuration.md
This PR updates
- the configuration doc for mito engine, especially its memtables
- the doc for table options
- adds compaction options
- adds append mode
fixes https://github.com/GreptimeTeam/docs/issues/863
> docs: update config and table options docs

- docs/v0.7/en/user-guide/concepts/storage-location.md
- docs/v0.7/zh/user-guide/concepts/storage-location.md
Fixed the broken links in storage location doc.
> fix: broken links to storage options

- docs/v0.7/en/reference/sql/create.md
- docs/v0.7/zh/reference/sql/create.md
This PR removes `append_mode` from docs of v0.7. I'll add it to the doc of the next version if it is ready.
> docs: remove append mode docs from v0.7

- .husky/commit-msg
- .husky/pre-commit
- package.json
- pnpm-lock.yaml
1. We don't force every commit but we can guard the PR title instead.
2. `pnpm build` for each commit is too expensive; we already have CI to guard the result.
This can close #911.
> build: simplify precommit

- script/build.js
- script/dev.js
Resolve #923.
We can run the following commands to add additional args:
```console
pnpm run dev --host 0.0.0.0 --port 5177
```
> refactor: accept additional args for running `pnpm run docs:dev`

- docs/nightly/en/user-guide/operations/region-migration.md
- docs/nightly/zh/user-guide/operations/region-migration.md
- docs/v0.7/en/user-guide/operations/region-migration.md
- docs/v0.7/zh/user-guide/operations/region-migration.md
> fix: incorrect format of migrate_region options

- docs/nightly/en/getting-started/installation/greptimedb-standalone.md
- docs/nightly/en/getting-started/quick-start/prerequisites.md
- docs/nightly/en/getting-started/quick-start/prometheus.md
- docs/nightly/en/getting-started/quick-start/vector.md
- docs/nightly/en/user-guide/clients/opentsdb.md
- docs/nightly/en/user-guide/operations/configuration.md
- docs/nightly/en/user-guide/operations/remote-wal/quick-start.md
- docs/nightly/en/user-guide/write-data/opentsdb.md
- docs/nightly/zh/getting-started/installation/greptimedb-standalone.md
- docs/nightly/zh/getting-started/quick-start/prerequisites.md
- docs/nightly/zh/getting-started/quick-start/prometheus.md
- docs/nightly/zh/getting-started/quick-start/vector.md
- docs/nightly/zh/user-guide/clients/opentsdb.md
- docs/nightly/zh/user-guide/operations/configuration.md
- docs/nightly/zh/user-guide/operations/remote-wal/quick-start.md
- docs/nightly/zh/user-guide/write-data/opentsdb.md
This pr mainly removes the OpenTSDB TCP/Telnet related docs.
wait for https://github.com/GreptimeTeam/greptimedb/pull/3828 to be merged first
closes #926
> chore: remove opentsdb telnet in nightly doc

- docs/nightly/en/reference/sql/copy.md
- docs/nightly/zh/reference/sql/copy.md
add doc for new option in `COPY TABLE FROM STMT`
relate to: https://github.com/GreptimeTeam/greptimedb/pull/3819
> docs: limit total rows copied in COPY TABLE FROM stmt

- docs/.vitepress/config/plugins.ts
- docs/nightly/en/db-cloud-shared/tutorials/monitor-host-metrics/prometheus-demo.md
- docs/nightly/en/getting-started/installation/greptimedb-standalone.md
- docs/nightly/en/getting-started/quick-start/prerequisites.md
- docs/nightly/en/getting-started/quick-start/prometheus.md
- docs/nightly/en/getting-started/quick-start/vector.md
- docs/nightly/en/user-guide/client-libraries/go.md
- docs/nightly/en/user-guide/client-libraries/java.md
- docs/nightly/variates.yml
- docs/nightly/zh/db-cloud-shared/tutorials/monitor-host-metrics/prometheus-demo.md
- docs/nightly/zh/getting-started/installation/greptimedb-standalone.md
- docs/nightly/zh/getting-started/quick-start/prerequisites.md
- docs/nightly/zh/getting-started/quick-start/prometheus.md
- docs/nightly/zh/getting-started/quick-start/vector.md
- docs/nightly/zh/user-guide/client-libraries/go.md
- docs/nightly/zh/user-guide/client-libraries/java.md
> docs: use variables for versions

- docs/nightly/en/reference/command-lines.md
- docs/nightly/en/user-guide/operations/configuration.md
- docs/nightly/zh/reference/command-lines.md
- docs/nightly/zh/user-guide/operations/configuration.md
Renames `metasrv_addr`, `store_addr` to `metasrv_addrs`, `store_addrs` in start command.
https://github.com/GreptimeTeam/greptimedb/pull/3921
https://github.com/GreptimeTeam/greptimedb/pull/3925
> docs: start command args

- docs/nightly/en/reference/sql/data-types.md
- docs/nightly/zh/reference/sql/data-types.md
This reflects the change introduced by https://github.com/GreptimeTeam/greptimedb/pull/3731.
> docs: Update data type alias

- docs/nightly/en/reference/sql/copy.md
- docs/nightly/zh/reference/sql/copy.md
releated to: https://github.com/GreptimeTeam/greptimedb/pull/3910
> docs: limit total rows copied in COPY TABLE FROM with LIMIT segment

- docs/nightly/en/reference/sql/functions.md
- docs/nightly/en/reference/sql/information-schema/partitions.md
- docs/nightly/en/user-guide/operations/admin.md
- docs/nightly/zh/reference/sql/functions.md
- docs/nightly/zh/reference/sql/information-schema/partitions.md
- docs/nightly/zh/user-guide/operations/admin.md
Fixed the docs about `partitions`.
> fix: partitions

- docs/nightly/en/user-guide/upgrade.md
- docs/nightly/zh/user-guide/upgrade.md
> docs: add upgrade note for using InfluxDB protocol

- docs/release-notes/release-0-8-0.md
> docs: add v0.8.0 highlights

- docs/nightly/zh/summary-i18n.yml
- docs/v0.8/zh/summary-i18n.yml
Flownode's content is present but the summary seems incorrect.
> fix: Chinese summary doesn't include flownode

- docs/nightly/en/reference/sql/create.md
- docs/nightly/zh/reference/sql/create.md
related to: https://github.com/GreptimeTeam/greptimedb/pull/4042
> docs: add docs for table level comment

- docs/nightly/en/user-guide/clients/influxdb-line.md
- docs/nightly/zh/user-guide/clients/influxdb-line.md
- docs/v0.8/en/user-guide/clients/influxdb-line.md
- docs/v0.8/zh/user-guide/clients/influxdb-line.md
Removed an invalid character before `curl` command in InfluxDB line protocol documents.
> fix: influxdb line protocol curl comand

- docs/nightly/en/greptimecloud/integrations/mysql.md
- docs/nightly/en/user-guide/client-libraries/java.md
- docs/nightly/zh/greptimecloud/integrations/mysql.md
- docs/nightly/zh/user-guide/client-libraries/java.md
- docs/v0.8/en/greptimecloud/integrations/mysql.md
- docs/v0.8/en/user-guide/client-libraries/java.md
- docs/v0.8/zh/greptimecloud/integrations/mysql.md
- docs/v0.8/zh/user-guide/client-libraries/java.md
Document for https://github.com/GreptimeTeam/greptimedb/issues/3887
Related PR https://github.com/GreptimeTeam/greptimedb/pull/4064
> feat: adds time zone setting for JDBC

- docs/nightly/en/getting-started/installation/greptimedb-standalone.md
- docs/nightly/zh/getting-started/installation/greptimedb-standalone.md
- docs/v0.5/en/getting-started/installation/greptimedb-standalone.md
- docs/v0.5/zh/getting-started/installation/greptimedb-standalone.md
- docs/v0.6/en/getting-started/installation/greptimedb-standalone.md
- docs/v0.6/zh/getting-started/installation/greptimedb-standalone.md
- docs/v0.7/en/getting-started/installation/greptimedb-standalone.md
- docs/v0.7/zh/getting-started/installation/greptimedb-standalone.md
- docs/v0.8/en/getting-started/installation/greptimedb-standalone.md
- docs/v0.8/zh/getting-started/installation/greptimedb-standalone.md
This PR mentions the default start command binds the address to `127.0.0.1` and gives an example to change the address to bind.
This fixes https://github.com/GreptimeTeam/docs/issues/975
> docs: mention default bind address

- .github/workflows/addDocsToS3BucketAWS.yml
Push china docs to s3 when main branch change.
Ignore english docs push s3 when merge main branch.
Workflows example: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
> chore: add 'paths-ignore' in addDocsToS3BucketAWS workflow

- docs/.vitepress/config/zh.ts
- docs/nightly/zh/faq-and-others/faq.md
- docs/nightly/zh/faq-and-others/overview.md
- docs/nightly/zh/summary-i18n.yml
- docs/v0.8/en/faq-and-others/overview.md
- docs/v0.8/zh/faq-and-others/faq.md
- docs/v0.8/zh/faq-and-others/overview.md
- docs/v0.8/zh/summary-i18n.yml
> docs: add release-notes and faq to the zh doc

- docs/nightly/en/reference/sql/information-schema/build-info.md
- docs/nightly/en/reference/sql/information-schema/cluster-info.md
- docs/nightly/en/reference/sql/information-schema/tables.md
- docs/nightly/zh/reference/sql/information-schema/build-info.md
- docs/nightly/zh/reference/sql/information-schema/cluster-info.md
- docs/nightly/zh/reference/sql/information-schema/tables.md
- docs/v0.9/en/reference/sql/information-schema/build-info.md
- docs/v0.9/en/reference/sql/information-schema/cluster-info.md
- docs/v0.9/en/reference/sql/information-schema/tables.md
- docs/v0.9/zh/reference/sql/information-schema/build-info.md
- docs/v0.9/zh/reference/sql/information-schema/cluster-info.md
- docs/v0.9/zh/reference/sql/information-schema/tables.md
Some tables schema in `information_schema` have been changed since v0.9.0, updated the documents to reflect them.
> docs: update some information_schema tables results

- docs/nightly/en/contributor-guide/getting-started.md
- docs/nightly/zh/contributor-guide/getting-started.md
- docs/v0.8/en/contributor-guide/getting-started.md
- docs/v0.8/zh/contributor-guide/getting-started.md
- docs/v0.9/en/contributor-guide/getting-started.md
- docs/v0.9/zh/contributor-guide/getting-started.md
Related to [discussion#4473](https://github.com/orgs/GreptimeTeam/discussions/4473)
> docs: fix supported operating systems

- docs/nightly/en/getting-started/installation/greptimedb-cluster.md
- docs/nightly/zh/getting-started/installation/greptimedb-cluster.md
- docs/v0.9/en/getting-started/installation/greptimedb-cluster.md
- docs/v0.9/en/getting-started/installation/overview.md
- docs/v0.9/zh/getting-started/installation/greptimedb-cluster.md
**Re-write** the cluster installation in quick-start:
- Use Docker Compose to deploy the greptimedb cluster instead of using `gtctl`(We always prefer to use container instead of pre-built binary);
- Use helm chart to deploy cluster in Kubernetes;
> refactor:  re-write the cluster installation of quick-start

- docs/user-guide/operations/configuration.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/operations/configuration.md
add `wal.auto_create_topics` option
close #1149
> feat: add `wal.auto_create_topics` option

- docs/user-guide/concepts/features-that-you-concern.md
- docs/user-guide/manage-data/overview.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/concepts/features-that-you-concern.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/manage-data/overview.md
> docs: TTL policy

- docs/reference/sql/functions/overview.md
- i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/functions/overview.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.9/reference/sql/functions/overview.md
- versioned_docs/version-0.9/reference/sql/functions/overview.md
> docs: update admin function doc

- docs/user-guide/logs/pipeline-config.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/pipeline-config.md
> remove dissect reference keys. because the resulting key is uncertain, it can't be specified by transform; if it is certain, you can use name matching to get the specified key directly.
* remove dissect dynamic key names. referable https://github.com/GreptimeTeam/greptimedb/pull/4571
> chore: remove dissect dynamic key names

- docs/user-guide/logs/manage-pipelines.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/manage-pipelines.md
* add doc for dryrun pipeline api
> chore: add doc for dryrun pipeline api

- docs/user-guide/protocols/http.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/protocols/http.md
Fixes #1181 
This patch includes arrow ipc http output format and others.
> docs: document arrow endpoint api

- docs/user-guide/deployments/deploy-on-kubernetes/deploy-greptimedb-cluster.md
- docs/user-guide/deployments/deploy-on-kubernetes/overview.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/deploy-on-kubernetes/deploy-greptimedb-cluster.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/deploy-on-kubernetes/overview.md
refactor GreptimeDB k8s deployment part
> refactor: refactor GreptimeDB k8s deployment part

- docs/getting-started/quick-start.md
- docs/reference/sql/create.md
- docs/user-guide/administration/manage-data/basic-table-operations.md
- docs/user-guide/administration/remote-wal/cluster-deployment.md
- i18n/zh/docusaurus-plugin-content-docs/current/getting-started/quick-start.md
- i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/create.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/administration/manage-data/basic-table-operations.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/administration/remote-wal/cluster-deployment.md
* No need to emphasize the default option
* There is no storage engine documentation yet, and emphasizing `engine=mito` confuse users.
> chore: remove `engine=mito` when creating tables

- .github/workflows/check-cloud-integration-link.yml
- docs/greptimecloud/integrations/dbeaver.md
- versioned_docs/version-0.9/greptimecloud/integrations/dbeaver.md
> fix: correct links for access page outside docs

- docs/getting-started/installation/greptimedb-cluster.md
- i18n/zh/docusaurus-plugin-content-docs/current/getting-started/installation/greptimedb-cluster.md
> refactor: add note for cluster deployment

- docs/reference/sql/information-schema/overview.md
- docs/reference/sql/information-schema/procedure-info.md
- i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/information-schema/overview.md
- i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/information-schema/procedure-info.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.9/reference/sql/information-schema/overview.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.9/reference/sql/information-schema/procedure-info.md
- versioned_docs/version-0.9/reference/sql/information-schema/overview.md
- versioned_docs/version-0.9/reference/sql/information-schema/procedure-info.md
add doc for procedure_info table
> docs: add doc for procedure_info table

- docs/reference/sql/alter.md
- i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/alter.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.9/reference/sql/alter.md
- versioned_docs/version-0.9/reference/sql/alter.md
closes #1249
- Introduce `SET <option_name>=<option_value>` syntax for `ALTER TABLE`.
- Document the `ttl` option for setting data retention time.
- Update English and Chinese documentation for current and version 0.9.
> docs: add support for altering table options in SQL documentation

- docs/user-guide/logs/pipeline-config.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/pipeline-config.md
> chore: add json path doc

- docs/reference/sql/alter.md
- docs/reference/sql/create.md
- i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/alter.md
- i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/create.md
Add docs for alter column fulltext options. Waiting for https://github.com/GreptimeTeam/greptimedb/pull/4952
Close #1277
> docs: update alter column fulltext options

- docs/reference/sql/data-types.md
- i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/data-types.md
The insert limitation has been removed in https://github.com/GreptimeTeam/greptimedb/pull/4893
> chore: remove json limitation

- docs/reference/sql/alter.md
- i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/alter.md
- closes #1283 
Enhance ALTER TABLE documentation with TWCS options
• Updated English and Chinese documentation for ALTER TABLE to include new options related to TWCS (Time Window Compaction Strategy).
• Added descriptions for compaction.twcs.time_window, max_output_file_size, max_active_window_runs, max_inactive_window_runs, max_active_window_files, and
max_inactive_window_files.
> docs: alter compaction options

- .github/workflows/addDocsToS3BucketAWS.yml
- .gitignore
This [GitHub Action](https://github.com/GreptimeTeam/docs/actions/runs/11893613364/job/33138990254) exists file `build/index.html` when upload to s3, but this [GitHub Action](https://github.com/GreptimeTeam/docs/actions/runs/11891985741/job/33133882053) does not exist. Add a step to confirm whether there is a build problem.
> ci: add step to check build directory files

- docs/user-guide/continuous-aggregation/manage-flow.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/continuous-aggregation/manage-flow.md
add docs for `OR REPLACE` section in `CREATE FLOW`
> docs: OR REPLACE

- i18n/zh/docusaurus-plugin-content-docs/version-0.9/reference/sql/alter.md
- versioned_docs/version-0.9/reference/sql/alter.md
Remove alter options section from v0.9 docs.
Related to https://github.com/GreptimeTeam/greptimedb/issues/5026
> docs: remove alter options docs from v0.9

- docs/reference/sql/alter.md
- i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/alter.md
add unset option syntax in alter table
> feat: add unset option syntax in alter table

- blog/release-0-10-2.md
* Make v0.10.1 deprecated.
* Copy and extend the release note of v0.10.1 into v0.10.2
> docs: release note v0.10.2

- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/pipeline-config.md
- versioned_docs/version-0.10/user-guide/logs/pipeline-config.md
Closes https://github.com/GreptimeTeam/docs/issues/1336
> feat: document decolorize processor

- docs/user-guide/deployments/configuration.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/configuration.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.10/user-guide/deployments/configuration.md
- versioned_docs/version-0.10/user-guide/deployments/configuration.md
> docs: add doc for backend's options

- docs/greptimecloud/integrations/postgresql.md
- docs/user-guide/protocols/postgresql.md
- i18n/zh/docusaurus-plugin-content-docs/current/greptimecloud/integrations/postgresql.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/protocols/postgresql.md
Fixes #1350 
Add information for postgres_fdw
> docs: postgres foreign data wrapper

- i18n/zh/docusaurus-plugin-content-docs/current/greptimecloud/integrations/mysql.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.10/greptimecloud/integrations/mysql.md
- package.json
> chore: fix dead links

- docs/user-guide/protocols/postgresql.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/protocols/postgresql.md
> docs: show create table for postgres_foreign_table

- docs/user-guide/integrations/grafana.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/integrations/grafana.md
Add an alternative installation method for grafana datasource plugin.
> docs: add greptime grafana docker image

- docs/user-guide/deployments/deploy-on-kubernetes/monitoring/cluster-monitoring-deployment.md
- docs/user-guide/deployments/deploy-on-kubernetes/overview.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/deploy-on-kubernetes/monitoring/cluster-monitoring-deployment.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/deploy-on-kubernetes/overview.md
- sidebars.ts
Add monitoring deployment for cluster on Kubernetes.
> docs: add cluster monitoring

- docs/user-guide/administration/remote-wal/cluster-deployment.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/administration/remote-wal/cluster-deployment.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.11/user-guide/administration/remote-wal/cluster-deployment.md
- versioned_docs/version-0.11/user-guide/administration/remote-wal/cluster-deployment.md
Fixed to: `2024-12-24 07:45:12 WARN  AbstractOperator:566 - Reconciliation #4(watch) Kafka(default/kafka-wal): Failed to reconcile io.strimzi.operator.cluster.model.KafkaVersion$UnsupportedKafkaVersionException: Unsupported Kafka.spec.kafka.version: 3.7.0. Supported versions are: [3.8.0, 3.8.1, 3.9.0]`
> fix: kafka deploy version

- docs/contributor-guide/datanode/data-persistence-indexing.md
- i18n/zh/docusaurus-plugin-content-docs/current/contributor-guide/datanode/data-persistence-indexing.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.11/contributor-guide/datanode/data-persistence-indexing.md
- versioned_docs/version-0.11/contributor-guide/datanode/data-persistence-indexing.md
> chore: adjust image size

- docs/user-guide/concepts/data-model.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/administration/performance-tuning-tips.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/concepts/data-model.md
This PR updates the create table statement in the data model section. It uses the recommended append-only table for logs.
It also updates the link in the zh performance guide.
> docs: update log example in data model

- blog/release-0-11-2.md
- blog/release-0-7-2.md
- docs/user-guide/administration/performance-tuning-tips.md
- docs/user-guide/deployments/configuration.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.11/user-guide/administration/performance-tuning-tips.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.11/user-guide/concepts/data-model.md
- versioned_docs/version-0.11/user-guide/administration/performance-tuning-tips.md
- versioned_docs/version-0.11/user-guide/concepts/data-model.md
- versioned_docs/version-0.11/user-guide/deployments/configuration.md
This PR adds the change log for v0.11.2 and updates cache-related docs for it.
It also update docs for https://github.com/GreptimeTeam/docs/issues/1423
> docs: release v0.11.2 and update cache related docs

- blog/release-0-11-2.md
- docs/user-guide/administration/performance-tuning-tips.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/administration/performance-tuning-tips.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/configuration.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.11/user-guide/administration/performance-tuning-tips.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.11/user-guide/deployments/configuration.md
- versioned_docs/version-0.11/user-guide/administration/performance-tuning-tips.md
Fixes https://github.com/GreptimeTeam/docs/issues/1423
Updates zh docs for https://github.com/GreptimeTeam/docs/pull/1424
Removes comments on write cache path as it always has a default value so users usually don't set it.
> docs: follow-up update of the zh docs for cache config

- docs/user-guide/administration/manage-etcd.md
- docs/user-guide/deployments/deploy-on-kubernetes/getting-started.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/administration/manage-etcd.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/deploy-on-kubernetes/getting-started.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.11/user-guide/administration/manage-etcd.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.11/user-guide/deployments/deploy-on-kubernetes/getting-started.md
- sidebars.ts
- versioned_docs/version-0.11/user-guide/administration/manage-etcd.md
- versioned_docs/version-0.11/user-guide/deployments/deploy-on-kubernetes/getting-started.md
- versioned_sidebars/version-0.11-sidebars.json
Add etcd cluster management documentation.
> feat: add manage etcd docs

- docs/user-guide/manage-data/data-index.md
- i18n/zh/docusaurus-plugin-content-docs/current/faq-and-others/faq.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/manage-data/data-index.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.11/user-guide/manage-data/data-index.md
- versioned_docs/version-0.11/user-guide/manage-data/data-index.md
Fix SQLs about index. Update FAQ about tantivy
> fix: update data index documentation for consistency and clarity

- docs/reference/sql/alter.md
Greptimedb supports add multiple columns as of https://github.com/GreptimeTeam/greptimedb/pull/5262.
> chore: add multiple columns

- docs/user-guide/manage-data/data-index.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/manage-data/data-index.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.11/user-guide/manage-data/data-index.md
- versioned_docs/version-0.11/user-guide/manage-data/data-index.md
> docs: add fulltext options to data index doc

- i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/alter.md
> chore: the ZH doc of adding multiple columns

- docs/user-guide/deployments/deploy-on-kubernetes/getting-started.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/deploy-on-kubernetes/getting-started.md
1. Use `self-monitoring` instead of `...monitoring integration...` and add more description of self-monitoring;
2. Enable `flownode` by default;
> refactor: refine k8s deployment quick start

- docs/user-guide/deployments/configuration.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/configuration.md
Correct index cache configuration
#1478
> chore: correct index cache config

- docs/user-guide/query-data/promql.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/query-data/promql.md
Update the limitation doc of promql
> feat: update limitation of promql

- blog/release-0-11-3.md
> docs: add 0.11.3 changelog

- docs/user-guide/logs/query-logs.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/query-logs.md
Remove `fulltext` and `matches` in the beginner guide. Use `LIKE` instead
> feat: rewrite the log user guide

- docs/user-guide/logs/pipeline-config.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/pipeline-config.md
Adding `skipping` to the pipeline index options.
closes #1542
> docs: add skipping index option in pipeline index

- docs/user-guide/deployments/run-on-android.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/run-on-android.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.10/user-guide/deployments/run-on-android.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.11/user-guide/deployments/run-on-android.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.12/user-guide/deployments/run-on-android.md
- versioned_docs/version-0.10/user-guide/deployments/run-on-android.md
- versioned_docs/version-0.11/user-guide/deployments/run-on-android.md
- versioned_docs/version-0.12/user-guide/deployments/run-on-android.md
- fix the script to fetch latest version of greptimedb
- **Configuration Update**: Changed the `grpc` configuration parameter from `addr` to `bind_addr` in `run-on-android.md` files.
> docs: update docs for runnng on android

- docs/reference/sql/data-types.md
Updated the `datetime` type usage.  
For https://github.com/GreptimeTeam/greptimedb/pull/5616
> docs: update `Datetime` type description

- docs/user-guide/deployments/configuration.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/configuration.md
fixes https://github.com/GreptimeTeam/docs/issues/1558
add `enable_virtual_host_style`
> docs: add config docs for enable_virtual_host_style

- docs/user-guide/query-data/promql.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/query-data/promql.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.13/user-guide/query-data/promql.md
- versioned_docs/version-0.13/user-guide/query-data/promql.md
Close #1515 
Close #1524
Close #1550
Close  #1551
> docs: add quantile, sort, sort_desc etc. to supported list for promql

- docs/contributor-guide/overview.md
- docs/reference/about-greptimedb-engines.md
- docs/reference/sql/create.md
- docs/user-guide/concepts/key-concepts.md
- i18n/zh/docusaurus-plugin-content-docs/current/contributor-guide/overview.md
- i18n/zh/docusaurus-plugin-content-docs/current/reference/about-greptimedb-engines.md
- i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/create.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/concepts/key-concepts.md
* Rename engines introduction doc.
* Adds links to the engine intro doc.
> docs: rename engine introduction and add links to it

- docs/user-guide/deployments/configuration.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/configuration.md
close #1610 
add `max_running_procedures` options
> feat: add `max_running_procedures`

- docs/reference/sql/information-schema/region-peers.md
- docs/reference/sql/show.md
- i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/information-schema/region-peers.md
- i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/show.md
close #1605 
1. add `Show Regions` statement
2. update `REGION_PEERS` doc
> feat: add `Show Regions` and update `REGION_PEERS` docs

- blog/release-0-13-1.md
- blog/release-0-13-2.md
> docs: add 0.13.1 & 0.13.2 changelog

- docs/reference/sql/explain.md
- i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/explain.md
Add SQL example for `EXPLAIN VERBOSE`.
Updates all other examples in the document.
fixes https://github.com/GreptimeTeam/docs/issues/1596
> docs: add explain analyze verbose example

- docs/reference/sql/overview.md
- docs/reference/sql/replace.md
- i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/overview.md
- i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/replace.md
- sidebars.ts
This PR adds a document for the `REPLACE` statement. In GreptimeDB, it is identical to `INSERT`. So the document mainly provides some simple examples.
fixes https://github.com/GreptimeTeam/docs/issues/1625
> docs: add docs for replace statement

- docs/user-guide/deployments/configuration.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/configuration.md
close #1617
remove backoff config
> docs: remove backoff config

- .github/workflows/addDocsToS3BucketAWS.yml
- .github/workflows/issue-notifier.yml
- docs/user-guide/deployments/deploy-on-kubernetes/common-helm-chart-configurations.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments/deploy-on-kubernetes/common-helm-chart-configurations.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.13/user-guide/deployments/deploy-on-kubernetes/common-helm-chart-configurations.md
- versioned_docs/version-0.13/user-guide/deployments/deploy-on-kubernetes/common-helm-chart-configurations.md
1. Rename `secretAccessKey` to `accessKeySecret`, related to: https://github.com/GreptimeTeam/helm-charts/pull/244
2. Bump greptimedb and debug pod image version
3. Set github workflow to run only in `GreptimeTeam/docs`
> chore: rename alicloud secret key

- docs/user-guide/ingest-data/for-observability/opentelemetry-traces.md
- docs/user-guide/ingest-data/for-observability/opentelemetry.md
- docs/user-guide/logs/write-logs.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/ingest-data/for-observability/opentelemetry-traces.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/ingest-data/for-observability/opentelemetry.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/write-logs.md
Add description about append_only mode in log/trace ingestion pages.
> docs: add append-only mode desc for log/trace table

- docs/getting-started/quick-start.md
- i18n/zh/docusaurus-plugin-content-docs/current/getting-started/quick-start.md
```
Invalid SQL syntax: sql parser error: Cannot use keyword 'log' as column name. Hint: add quotes to the name.
```
> docs: log is in sql keywords now

- docs/user-guide/flow-computation/continuous-aggregation.md
- docs/user-guide/flow-computation/manage-flow.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/flow-computation/continuous-aggregation.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/flow-computation/manage-flow.md
emphasis expire after concept in user guide examples, and in manage flows.md
> docs: emphasis expire after concept

- docs/user-guide/ingest-data/for-observability/prometheus.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/ingest-data/for-observability/prometheus.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.14/user-guide/ingest-data/for-observability/prometheus.md
- versioned_docs/version-0.14/user-guide/ingest-data/for-observability/prometheus.md
* Correcting the wrong default metric engine table name
> chore: fix metric engine default table name

- docs/user-guide/concepts/why-greptimedb.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/concepts/why-greptimedb.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.14/user-guide/concepts/why-greptimedb.md
- versioned_docs/version-0.14/user-guide/concepts/why-greptimedb.md
The sql in example in user guide overview was removed. Replace it with getting started example.
> fix: broken links to sql example

- .github/workflows/addDocsToS3BucketAWS.yml
https://github.com/peak/s5cmd?tab=readme-ov-file#numworkers
The default worker number of the s5cmd tool is 256. Set it to 1024 can help us increase the speed of uploading files.
> ci: improve the speed of sync files to s3

- docs/reference/sql/functions/df-functions.md
- docs/reference/sql/functions/overview.md
- i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/functions/df-functions.md
- i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/functions/overview.md
* DataFusion already supports `greatest` function, so remove the custom `greatest` doc https://github.com/GreptimeTeam/greptimedb/pull/5994
* Updated DataFusion functions reference.
> docs: remove greatest function and update datafusion functions ref

- docs/user-guide/query-data/promql.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/query-data/promql.md
`count` is missing in https://github.com/GreptimeTeam/docs/pull/1581
`clamp` is from https://github.com/GreptimeTeam/greptimedb/pull/3465
`predicate_linear` is from https://github.com/GreptimeTeam/greptimedb/pull/1362
> docs: update promql function list to include clamp, count and predicate_linear

- docs/greptimecloud/integrations/otlp.md
- docs/user-guide/ingest-data/for-observability/opentelemetry.md
- i18n/zh/docusaurus-plugin-content-docs/current/greptimecloud/integrations/otlp.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/ingest-data/for-observability/opentelemetry.md
> chore: add otlp collector config example

- i18n/zh/docusaurus-plugin-content-docs/version-0.14/greptimecloud/integrations/otlp.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.14/user-guide/ingest-data/for-observability/opentelemetry.md
- versioned_docs/version-0.14/greptimecloud/integrations/otlp.md
- versioned_docs/version-0.14/user-guide/ingest-data/for-observability/opentelemetry.md
* copy otel collector config from current version to 0.14 close https://github.com/GreptimeTeam/docs/issues/1754
* this pr is a copy of https://github.com/GreptimeTeam/docs/pull/1744
> chore: copy otel collector docs to 0.14

- docs/user-guide/administration/monitoring/export-metrics.md
- docs/user-guide/administration/monitoring/tracing.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/administration/monitoring/export-metrics.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/administration/monitoring/tracing.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.14/user-guide/administration/monitoring/export-metrics.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.14/user-guide/administration/monitoring/tracing.md
- versioned_docs/version-0.14/user-guide/administration/monitoring/export-metrics.md
- versioned_docs/version-0.14/user-guide/administration/monitoring/tracing.md
Improve monitoring docs, close #1771 
1. Adds Grafana dashboard.
2. Fixed outdated content
3. Adds db version to links.
4. Fixed db name in exporting metrics settings.
> docs: improve monitoring docs

- docs/user-guide/deployments-administration/deploy-on-kubernetes/common-helm-chart-configurations.md
- docs/user-guide/deployments-administration/manage-data/region-failover.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments-administration/deploy-on-kubernetes/common-helm-chart-configurations.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments-administration/manage-data/region-failover.md
- Add detailed Region Failover configuration section in common-helm-chart-configurations.md
- Refactor region-failover.md to reference the new configuration guide
- Update both English and Chinese documentation
> docs: add Region Failover configuration guide

- docs/user-guide/deployments-administration/configuration.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments-administration/configuration.md
- **Added gRPC TLS Configuration**: Updated TLS configuration options to include gRPC interface in both English and Chinese documentation files.
- Files affected: `docs/user-guide/deployments-administration/configuration.md`, `i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments-administration/configuration.md`
> docs: grpc tls options

- docs/user-guide/deployments-administration/maintenance-mode.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments-administration/maintenance-mode.md
Update maintenance mode API endpoints
This PR should be merged after the release of version 0.15.0
> docs: update maintenance mode API endpoints

- docs/user-guide/protocols/mysql.md
- docs/user-guide/protocols/postgresql.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/protocols/mysql.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/protocols/postgresql.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.15/user-guide/protocols/mysql.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.15/user-guide/protocols/postgresql.md
- versioned_docs/version-0.15/user-guide/protocols/mysql.md
- versioned_docs/version-0.15/user-guide/protocols/postgresql.md
Add sections about `max_execution_time` for MySQL protocol and `statement_timeout` for PostgreSQL protocol.
> docs: add document for max_execution_time and statement_timeout

- docs/enterprise/deployments/deploy-on-kubernetes/installation.md
- docs/user-guide/deployments-administration/deploy-on-kubernetes/deploy-greptimedb-cluster.md
- i18n/zh/docusaurus-plugin-content-docs/current/enterprise/deployments/deploy-on-kubernetes/installation.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments-administration/deploy-on-kubernetes/deploy-greptimedb-cluster.md
- remove duplicate content between enterprise and oss
- Add EN doc for deploy GreptimeDB enterprise (part 1)
I will also apply these changes to v0.15 after reviewed
> chore: de-duplication between enterprise and OSS deployments

- docs/user-guide/logs/write-logs.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/logs/write-logs.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.14/user-guide/logs/write-logs.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.15/user-guide/logs/write-logs.md
- versioned_docs/version-0.14/user-guide/logs/write-logs.md
- versioned_docs/version-0.15/user-guide/logs/write-logs.md
This PR adds some config examples about the custom time index.
Backported to v0.15 and v0.14
> chore: examples about custom time index

- docs/user-guide/query-data/promql.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/query-data/promql.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.15/user-guide/query-data/promql.md
- versioned_docs/version-0.15/user-guide/query-data/promql.md
The `sort_by_label` and `sort_by_label_desc` are already supported.
https://github.com/GreptimeTeam/greptimedb/blob/main/src/query/src/promql/planner.rs#L809-L816
> docs: already supports sort_by_label etc.

- docs/enterprise/deployments-administration/monitoring/check-db-status.md
- docs/user-guide/deployments-administration/monitoring/check-db-status.md
- i18n/zh/docusaurus-plugin-content-docs/current/enterprise/deployments-administration/monitoring/check-db-status.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments-administration/monitoring/check-db-status.md
- sidebars.ts
> chore: move db status to OSS documentation

- docs/user-guide/deployments-administration/configuration.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments-administration/configuration.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.15/user-guide/deployments-administration/configuration.md
- versioned_docs/version-0.15/user-guide/deployments-administration/configuration.md
> fix: remove self_import from frontend

- .github/workflows/bump-nightly-version.yml
do not commit `package-lock.json`
> fix: only commit ts file when bumping nightly version

- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/flow-computation/manage-flow.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.11/user-guide/flow-computation/manage-flow.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.12/user-guide/flow-computation/manage-flow.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.13/user-guide/flow-computation/manage-flow.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.14/user-guide/flow-computation/manage-flow.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.15/user-guide/flow-computation/manage-flow.md
Remove redundant English instruction "To delete a flow, use the following `DROP FLOW` clause:" from Chinese documentation in all versions of manage-flow.md files. The Chinese translation of this instruction was already present.
> docs(i18n): remove English text from Chinese documentation

- docs/user-guide/deployments-administration/deploy-on-kubernetes/common-helm-chart-configurations.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments-administration/deploy-on-kubernetes/common-helm-chart-configurations.md
- i18n/zh/docusaurus-plugin-content-docs/version-0.15/user-guide/deployments-administration/deploy-on-kubernetes/common-helm-chart-configurations.md
- versioned_docs/version-0.15/user-guide/deployments-administration/deploy-on-kubernetes/common-helm-chart-configurations.md
Add TOS object storage configuration and write Volcengine TOS with the S3 protocol.
> feat: add volcengine TOS object storage configuration

- docs/reference/sql/create.md
- docs/reference/sql/data-types.md
- docs/user-guide/deployments-administration/performance-tuning/performance-tuning-tips.md
- docs/user-guide/timezone.md
- i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/create.md
- i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/data-types.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/deployments-administration/performance-tuning/performance-tuning-tips.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/timezone.md
1. Dashboard timezone settings
2. `INTERVAL` keyword
> docs: dashboard timezone settings and interval keyword

- docs/user-guide/traces/read-write.md
- i18n/zh/docusaurus-plugin-content-docs/current/user-guide/traces/read-write.md
According to OTEL docs, the trace endpoint should include `/v1/traces` in the endpoint: https://opentelemetry.io/docs/languages/sdk-configuration/otlp-exporter/#otel_exporter_otlp_traces_endpoint
> fix: otel trace endpoint config

- docusaurus.config.ts
* version command need two  locales to generate all locale content
> fix: locale versioning

- docs/reference/sql/information-schema/region-statistics.md
- i18n/zh/docusaurus-plugin-content-docs/current/reference/sql/information-schema/region-statistics.md
> feat: add `written_bytes_since_open` desc

- blog/release-0-17-1.md
> fix: correct release note title

- docs/enterprise/deployments-administration/deploy-on-kubernetes/configure-datanode-groups.md
- i18n/zh/docusaurus-plugin-content-docs/current/enterprise/deployments-administration/deploy-on-kubernetes/configure-datanode-groups.md
- sidebars.ts
> docs: add datanode grouping doc

- CONTRIBUTING.md
- docusaurus.config.ts
- package.json
- static/js/locale-switch.js
#2131 #2132
* keep url when nav to other locale site.
because docusaurus swizzle  mark LocaleDropdown as unsafe, so not use React Component for implementation.
> feat: i18n link
